### ISSUE TITLE
The book class needs a \title, \subtitle, \author

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#930] opened 2020-07-10 10:10 UTC
Having to do this is bonkers

https://github.com/sile-typesetter/sile/blob/d205c54ae5e16133a0f05e993d5da9051d3608cc/documentation/sile.sil#L23
https://github.com/sile-typesetter/sile/blob/d205c54ae5e16133a0f05e993d5da9051d3608cc/documentation/sile.sil#L26

**Comment by alerque** [comment] 2020-07-10 10:33
This is a duplicate of #599, #601, and others. The short version is that for books I use [CaSILE](https://github.com/sile-typesetter/casile/) anyway which has this machinery and a lot more (title pages, book covers, etc.). But yes, some of that work needs to be upstreamed into SILE.

**Closed** 2020-07-10 10:33 UTC
Labels: duplicate
