### ISSUE TITLE
Paragraph indent applied twice, inside and outside hboxes at paragraph start

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1718] opened 2023-02-23 09:02 UTC
SILE 0.14.8 (also tested on 0.12.5)

Initially found by  @nphyx 

**MWE**

```
\begin{document}
\use[module=packages.rules]
\use[module=packages.rotate]

\noindent{}Lorem...

Lorem (paragraph indented)

\underline{ipsum}

\rotate[angle=5]{dolor}

\boxaround{toto}% deprecated command, but just to show it there too

\end{document}
```

**Expected**

The content underlined / rotated / boxed should not include the paragraph indent inside it.

**Observed**

![image](https://user-images.githubusercontent.com/18075640/220862597-4cdaae57-efb2-4168-982b-047a47ec9b01.png)

**Comment by Omikhleia** [comment] 2023-02-23 09:18
Besides the issue as reported by the user, it turns out I had separately hit the same core problem for paragraphs with a _negative_ parindent (and lskip in effect, so to have the whole paragraph indented on all lines but not the first), and I resorted to a kind of hack to compute the width of an initial content (for use in my new footnotes).

https://github.com/Omikhleia/resilient.sile/blob/9cd95ba206b594eea38717cb32e418bad79d19fb/packages/resilient/styles/init.lua#L411-L421

**Comment by Omikhleia** [comment] 2023-02-23 19:36
Note that with the state introduced in proposal #1702, it seems it becomes a no-brainer fix actually: the typesetter should not init a new line within the context of an hbox creation, so:

```
function typesetter:initline ()
  if self.state.hmodeOnly then return end -- ADDED HERE
  if (#self.state.nodes == 0) then
    self.state.nodes[#self.state.nodes+1] = SILE.nodefactory.zerohbox()
    SILE.documentState.documentClass.newPar(self)
  end
end
```

**Comment by Omikhleia** [comment] 2023-02-23 20:26
And it also seems, in my own case, that I can get rid of my "hack" with negative parindent (or even avoid the negative parindent wholly, now, with a well placed kern instead, since the box gets exactly where it ought to be)

![image](https://user-images.githubusercontent.com/18075640/221021920-92b82c26-188a-4e99-947c-05cf7adc6703.png)

**Comment by alerque** [comment] 2023-04-10 20:44
It seems #1770 is a duplicate of this issue and is fixed by the proposed solution. I've opened a PR that includes a test for this case.

**Closed** 2023-04-10 21:27 UTC
Labels: bug
