### ISSUE TITLE
Docker image `siletypesetter/sile:latest` seems broken?

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1212] opened 2021-09-09 00:15 UTC
```
[fred@🍇葡萄🍇SILE]$ docker run -it --volume "/usr/share/fonts:/fonts" --volume "$(pwd):/data" --user "$(id -u):$(id -g)" siletypesetter/sile:latest
Unable to find image 'siletypesetter/sile:latest' locally
latest: Pulling from siletypesetter/sile
3cebb2be42a5: Pull complete 
ea4b88892555: Pull complete 
207849b83b60: Pull complete 
58653039bd47: Pull complete 
87ffd86569c5: Pull complete 
8c895c379b4e: Pull complete 
7106344c4f72: Pull complete 
4f4fb700ef54: Pull complete 
fe860da897c2: Pull complete 
Digest: sha256:8641d6ee4bee962d24fd82a3cd1db433a0dd8c86ceadc6d36520677486aaede5
Status: Downloaded newer image for siletypesetter/sile:latest
SILE v0.11.1 (Lua 5.4)
/usr/sbin/lua: error loading module 'justenoughlibtexpdf' from file './core/justenoughlibtexpdf.so':
	libtexpdf.so.0: cannot open shared object file: No such file or directory
stack traceback:
	[C]: in ?
	[C]: in function 'require'
	./core/libtexpdf-output.lua:1: in main chunk
	[C]: in function 'require'
	./core/sile.lua:77: in function 'core/sile.init'
	/usr/local/bin/sile:44: in main chunk
	[C]: in ?
```

**Comment by alerque** [comment] 2021-09-09 21:20
I am unable to replicate this. I even get the same Digest checksum for the image I downloaded.

```console
$ docker pull siletypesetter/sile:latest
latest: Pulling from siletypesetter/sile
Digest: sha256:8641d6ee4bee962d24fd82a3cd1db433a0dd8c86ceadc6d36520677486aaede5
Status: Image is up to date for siletypesetter/sile:latest
docker.io/siletypesetter/sile:latest
$ docker run -it --volume "/usr/share/fonts:/fonts" --volume "$(pwd):/data" --user "$(id -u):$(id -g)" siletypesetter/sile:latest
SILE v0.11.1 (Lua 5.4)
> SU.dump{"seems good?"}
{
  "seems good?"
>
```

I also use the same image to build some actual SIL files and got valid PDFs.

What is in whatever your `$(pwd)` is? Are you in half-built checkout of the SILE source code? Is it possible that mounting that into `/data` is messing up your include path and it's finding things in the CWD before the system paths in the Docker image?

**Comment by ctrlcctrlv** [comment] 2021-09-10 00:26
@alerque I was CD'd into the `sile` directory yes. Thanks a lot for helping me figure this out.

```
[fred@🍇葡萄🍇~]$ cd `mktemp -d`
[fred@🍇葡萄🍇tmp.l9avpe7mCM]$ docker run -it --volume "/usr/share/fonts:/fonts" --volume "$(pwd):/data" --user "$(id -u):$(id -g)" siletypesetter/sile:latest
SILE v0.11.1 (Lua 5.4)
> SILE.typesetter.typeset
function: 0x55b2ade0cb30
> 2+2
4
>
```

**Comment by alerque** [comment] 2021-09-18 15:16
This should get fixed with some sort of clean function in the Docker build. We already do this for libtexpdf, but the other generated files need similar resets in case the host environment is not like the Docker image. In my case both are current Arch Linux and so this didn't trip me up, but there is no reason we should assume that. Once in the container we should assume a clean-room type environment.

**Comment by nastarovia** [comment] 2021-09-18 15:18
P

**Comment by alerque** [comment] 2021-09-18 15:43
Bah! So many different systems my head is spinning trying to work on them all at once.

This really *is* equivalent to the Nix issue, but [like I said there](https://github.com/sile-typesetter/sile/pull/1231#discussion_r711603981) the problem isn't in the build environment. Both the Nix build and Docker get built fine, what goes sideways is trying to **run them** anywhere near the SILE source.

Personally I test those outside of the source anyway. Of course I mostly test host-system builds outside of the source tree too (with `./configure --datarootdir=$(cd ..;pwd)`, then calling sile using `/path/to/sile/sile <input>`).

I'm not sure what mechanism this would even need, but probably just some detection of if we are...

a) in the SILE source tree and
b) using Docker or Nix instead of a host build

...to prefer container resources over local ones.

But then again, what is the actual use case here? Wouldn't that just make it *harder* to fiddle with the SILE sources while testing it on those platforms?

**Comment by alerque** [comment] 2022-01-12 16:57
I'm going to close this as *won't fix* because I can't think of any better way for it to work. The whole point of SILE being written in Lua and modular and checking the `$CWD` for anything it needs to load is that any part of the system *should* be replaceable at run time. As such this is working as expected. If you supply something locally it is assumed to work with the running `sile` even if that is a containerized one. We could block this, but we'd also block *expected* behaviors.

I'm open to more feedback if there is something I'm missing.

**Closed by alerque** 2022-01-12 16:57 UTC
Labels: builds & releases
