### ISSUE TITLE
Pagebreak doesn't work 

### ISSUE THREAD

**Issue by Eli-the-Bearded** [sile-typesetter/sile#543] opened 2018-11-28 06:10 UTC
Either `\pagebreak` doesn't work, or is not documented correctly.

The manual says:

> `\code{\\pagebreak}` (also known as `\code{\\supereject}`) is a more forceful variant, and ensures that a new page is opened even if there are remaining frames on the page.

This simple document:
```
\begin[class=book]{document}
Demo
\pagebreak
File
\end{document}
```

Produces a single page PDF. (`\supereject` does work, but looks ugly to me.)

**Comment by alerque** [comment] 2018-12-05 06:41
You are correct, this is a case of bogus documentation. The definitions of those functions show one glaring difference — one fills the page with as much vertical space as it can, then adds a break, the other just adds a break point.

```TeX
\define[command=pagebreak]{\penalty[penalty=-20000]}%
\define[command=supereject]{\vfill\penalty[penalty=-20000]}%
```

**Comment by simoncozens** [comment] 2018-12-12 13:03
There are differences, and the documentation is wrong, but something else is wrong here too. What *should* happen is:

`\pagebreak` creates a non-negotiable breakpoint, and all stretchy vglues on the page should be expanded to fill up the remaining space as much as possible.
`\supereject` creates a non-negotiable breakpoint but inserts infinitely stretchy vglue so that the other vglues on the page stay at their natural size.

This should be clarified in the documentation, but at the same time the page break mechanism isn't seeing a massive negative breakpoint as non-negotiable, so there's something wrong there too.

**Comment by Omikhleia** [comment] 2022-11-22 19:30
I was mislead too by the fact that the documentation equates `\pagebreak` and `\supereject`, and seeing in the code that it isn't true, I was about to open an issue... when I found this one. 

The documentation really ought to be fixed.

But apart from the documentation issue, I can't be sure what @simoncozens wanted to say when he wrote:
> but at the same time the page break mechanism isn't seeing a massive negative breakpoint as non-negotiable, so there's something wrong there too.

Still, the example above uses `\pagebreak` in horizontal mode (in the same paragraph). That's _indeed_ going to be ignored here, because:
- it then applies to the line breaking mechanism, **not** to the page breaking algorithm ;)
- there's no such thing as a penalty lower than -10000 in the line breaking logic ;)

As noted by the initial poster, `\supereject` works... because its `\vfill` causes the horizontal mode to be left ;)

Hence, I think `\pagebreak` should be fixed:

https://github.com/sile-typesetter/sile/blob/1a86520d198d7709966e1fd1bfd8dfaceda86393/classes/plain.lua#L172

This should be, in my opinion:
```suggestion
SILE.call("penalty", { penalty = -20000, vertical = true })
```
(Well, either that, or it should have a `SILE.typesetter.leaveHmode()` before it)

And then of course the suggested documentation changes then apply too... Er. Wait.

Exact same kind of issue for:
> The commands \framebreak and \eject are also available as synonyms.

The `\eject` command calls `\vfill` too (and the only difference with `\superject` is the penalty value).

The `\framebreak` is **not** a synonym, it doesn't have the vertical fill.
It doesn't leave horizontal mode (either explicitly or via the vertical=true option), so here too, if invoked in horizontal content; it apply to the line breaking logic, not to the page breaking logic. But the penalty value (here a regular "break", so -10000) works there! So a "framebreak" in horizontal mode ends up being a mere line break. I'm pretty sure it wasn't the intent too, or these things are badly named...

**Comment by Omikhleia** [comment] 2022-11-23 00:03
I'll make a PR... But that a 4-year old issue with a reproduction scenario is still open, this is... Shhh. Triage, folks! ;)

**Closed** 2022-11-29 11:12 UTC
Labels: bug, documentation
