### ISSUE TITLE
open-double-page is (almost) broken

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#1283] opened 2021-11-12 12:46 UTC
SILE 0.12

The "open-double-page" command from the "twoside" package doesn't work well.
- If the document starts with a chapter directly (so you are already on an odd page)... Then one gets blank initial pages.
- Likewise if the previous content within the book already ejected the page (e.g. because one needed to vfill something at the bottom properly), one gets extra blank page.

But having it inside the "twoside" package might also be a wrong separation of concerns: As implemented, the "blank" page that will get inserted if needed will likely get page numbers and headers. This is at the least controversial, and should be a (book) class decision - so perhaps to consider there https://github.com/sile-typesetter/sile/projects/2#card-42057180

_As an aside note_, in my in-progress book class I ended up not using it. The re-implementation inside that book class cannot just be reused as-is, though, as it relies on another feature (= mostly, an abstraction of the headers as we have it for the folios, with "headers / noheaders / noheaderthispage"). Commenting that part, it comes along the lines of:

```
SILE.registerCommand("omibook-double-page", function (_, _)
  SILE.typesetter:leaveHmode() -- Important, flushes output queue.
  if #SILE.typesetter.state.outputQueue ~= 0 then
    -- We are not at the top of a page, eject the current content.
    SILE.call("supereject")
  end
  SILE.typesetter:leaveHmode() -- Important again.
  if not SILE.documentState.documentClass:oddPage() then
    SILE.typesetter:typeset("")
    SILE.typesetter:leaveHmode()
    SILE.call("nofoliosthispage")
    -- SILE.call("noheaderthispage") -- Commented 
    SILE.call("supereject")
  end
  SILE.typesetter:leaveHmode() -- and again!
end, "Open a double page without header and folio")
```

When I see all the tasks listed in the "Redesign the book class" project, I am not sure where it will go.

**Comment by alerque** [comment] 2021-12-16 12:50
Duplicate of #454.

----

My current implementation is at:

https://github.com/sile-typesetter/casile/blob/6529e93163add0ec9c2ff87dee52b437595108b7/casile.lua#L213-L232

**Closed by alerque** 2021-12-16 12:50 UTC
