### ISSUE TITLE
Font file with invalid family name causes crash

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1015] opened 2020-08-06 12:09 UTC
Perhaps Roboto Condensed in Ubuntu repos is bad?

I have some changes I want to PR to the manual, but can't build it.

```
$ sile -t documentation/sile.sil 2>&1|cat -v
```

```
parseName: 	^@^@^@^W^A^Z^@^A^@^@^@^@^@^A^@^@^@^@^@^A^@^@^@^@^@^B^@^A^@^@^@^A^@^@^@^@^@^C^@^@^@^A^@^A^@^@^@^@^@^D^@&^@^A^@^A^@^@^@^@^@^F^@^A^@'^@^C^@^A^D	^@^@^@>^@(^@^C^@^A^D	^@^A^@^D^@f^@^C^@^A^D	^@^B^@^@^@j^@^C^@^A^D	^@^C^@^@^@j^@^C^@^A^D	^@^D^@^D^@j^@^C^@^A^D	^@^E^@,^@n^@^C^@^A^D	^@^F^@^B^@M-^Z^@^C^@^A^D	^@^G^@T^@M-^\^@^C^@^A^D	^@	^@^L^@M-p^@^C^@^A^D	^@^K^@^T^@M-|^@^C^@^A^D	^@^L^@&^A^P^@^C^@^A^D	^@^M^@\^A6^@^C^@^A^D	^@^N^@T^AM-^R^@^C^@^A^D	^@^P^@ ^AM-f^@^C^@^A^D	^@^Q^@
^B^F^@^C^@^A^D	^@^R^@,^B^P^@^C^@^A^D	^@M-H^@^V^B<^@^C^@^A^D	^@M-I^@0^BR^?Roboto Condensed Light Regular Webfont^?^@F^@o^@n^@t^@ ^@d^@a^@t^@a^@ ^@c^@o^@p^@y^@r^@i^@g^@h^@t^@ ^@G^@o^@o^@g^@l^@e^@ ^@2^@0^@1^@2^@.^@^?^@.^@^?^@V^@e^@r^@s^@i^@o^@n^@ ^@1^@.^@1^@0^@0^@1^@4^@1^@;^@ ^@2^@0^@1^@3^@^?^@R^@o^@b^@o^@t^@o^@ ^@C^@o^@n^@d^@e^@n^@s^@e^@d^@ ^@i^@s^@ ^@a^@ ^@t^@r^@a^@d^@e^@m^@a^@r^@k^@ ^@o^@f^@ ^@G^@o^@o^@g^@l^@e^@.^@G^@o^@o^@g^@l^@e^@G^@o^@o^@g^@l^@e^@.^@c^@o^@m^@C^@h^@r^@i^@s^@t^@i^@a^@n^@ ^@R^@o^@b^@e^@r^@t^@s^@o^@n^@L^@i^@c^@e^@n^@s^@e^@d^@ ^@u^@n^@d^@e^@r^@ ^@t^@h^@e^@ ^@A^@p^@a^@c^@h^@e^@ ^@L^@i^@c^@e^@n^@s^@e^@,^@ ^@V^@e^@r^@s^@i^@o^@n^@ ^@2^@.^@0^@h^@t^@t^@p^@:^@/^@/^@w^@w^@w^@.^@a^@p^@a^@c^@h^@e^@.^@o^@r^@g^@/^@l^@i^@c^@e^@n^@s^@e^@s^@/^@L^@I^@C^@E^@N^@S^@E^@-^@2^@.^@0^@R^@o^@b^@o^@t^@o^@ ^@C^@o^@n^@d^@e^@n^@s^@e^@d^@L^@i^@g^@h^@t^@R^@o^@b^@o^@t^@o^@ ^@C^@o^@n^@d^@e^@n^@s^@e^@d^@ ^@L^@i^@g^@h^@t^@W^@e^@b^@f^@o^@n^@t^@ ^@1^@.^@0^@T^@h^@u^@ ^@N^@o^@v^@ ^@ ^@7^@ ^@1^@5^@:^@2^@9^@:^@5^@0^@ ^@2^@0^@1^@3

Error detected:
	./lua_modules/share/lua/5.2/vstruct/io/s.lua:12: attempt to get length of local 'buf' (a nil value)
stack traceback:
	./lua_modules/share/lua/5.2/vstruct/io/s.lua:12: in function <./lua_modules/share/lua/5.2/vstruct/io/s.lua:10>
	(...tail calls...)
	./lua_modules/share/lua/5.2/vstruct/ast/Name.lua:47: in function 'read'
	./lua_modules/share/lua/5.2/vstruct/ast/Node.lua:39: in function 'read'
	./lua_modules/share/lua/5.2/vstruct/ast/Root.lua:12: in function <./lua_modules/share/lua/5.2/vstruct/ast/Root.lua:10>
	(...tail calls...)
	./core/opentype-parser.lua:96: in function 'parseName'
	./core/opentype-parser.lua:191: in function 'parseFont'
	./packages/color-fonts.lua:9: in function 'shapeToken'
	./packages/color-fonts.lua:49: in function 'createNnodes'
	./core/nodefactory.lua:257: in function 'shape'
	./core/typesetter.lua:283: in function 'shapeAllNodes'
	...
	./core/inputs-texlike.lua:169: in function 'process'
	./core/sile.lua:246: in function 'readFile'
	./core/baseclass.lua:114: in function '?'
	./core/sile.lua:293: in function 'call'
	./core/inputs-common.lua:65: in function 'process'
	./core/inputs-texlike.lua:169: in function 'process'
	./core/sile.lua:246: in function 'readFile'
	/opt/bin/sile:62: in function </opt/bin/sile:62>
	[C]: in function 'xpcall'
	/opt/bin/sile:62: in main chunk
	[C]: in ?
```

I applied this patch to get that debug output real quick after seeing crash on `parseName` the first time:

```diff
diff --git a/core/opentype-parser.lua b/core/opentype-parser.lua
index 29782b89..314a28a9 100644
--- a/core/opentype-parser.lua
+++ b/core/opentype-parser.lua
@@ -3,6 +3,7 @@ local hb = require "justenoughharfbuzz"
 local zlib = require "zlib"
 
 local parseName = function(str)
+  print("\nparseName: ", str)
   if str:len() <= 0 then return end
   local fd = vstruct.cursor(str)
```

Weirdly, this _does not_ result in a crash:

```tex
% nocrash.sil
\begin{document}
\script[src=packages/font-fallback]
\font:add-fallback[family=Symbola]
\font:add-fallback[family=Noto Sans CJK JP]
\font[family=Roboto Condensed]
あば x 😼 Hello world. あ
\end{document}
```

If we specify `-d fonts`, we see at end...

```
[fonts] Looking for Libertinus Serif;33;400;;normal;;LTR
[fonts] Resolved font family 'Libertinus Serif' -> /usr/share/fonts/truetype/freefont/FreeMono.ttf
[fonts] Looking for Gentium Book Basic;11;400;italic;normal;;LTR
[fonts] Resolved font family 'Gentium Book Basic' -> /home/osboxes/.local/share/fonts/GenBkBasI.ttf[31] <packages/raiselower><packages/grid>[32] [33] <packages/linespacing>
[fonts] Looking for Gentium Book Basic;20;400;;normal;;LTR
[fonts] Resolved font family 'Gentium Book Basic' -> /home/osboxes/.local/share/fonts/GenBkBasR.ttf<packages/verbatim>[34] <packages/font-fallback>
[fonts] Queue: {1={start=1,stop=284},2={popFallbacks=true}}
[fonts] table: 0x562810634d00
[fonts] Trying font 'Gentium Book Basic' for 'What happens when SILE is asked to typeset a character which is not in the current font? For instance, we are currently using the M-bM-^@M-^\GentiumM-bM-^@M-^] font, which covers a wide range of European scripts; however, it doesnM-bM-^@M-^Yt contain any Japanese character. So what if I ask SILE to typeset '
...
[fonts] Trying font 'Roboto Condensed' for 'color-fonts'
[fonts] Found glyph 'c'
[fonts] Found glyph 'o'
[fonts] Found glyph 'l'
[fonts] Found glyph 'o'
[fonts] Found glyph 'r'
[fonts] Found glyph '-'
[fonts] Found glyph 'f'
[fonts] Found glyph 'o'
[fonts] Found glyph 'n'
[fonts] Found glyph 't'
[fonts] Found glyph 's'
[fonts] Queue: {1={popFallbacks=true}}
[fonts] table: 0x5627fe591830
[fonts] table: 0x562805fd89b0
[fonts] Shaping color-fonts in Roboto Condensed
[fonts] table: 0x56280a0b8440
[fonts] Queue: {1={start=1,stop=1},2={popFallbacks=true}}
[fonts] table: 0x5628065d02a0
[fonts] Trying font 'Gentium Book Basic' for 'x'
[fonts] Found glyph 'x'
[fonts] Queue: {1={popFallbacks=true}}
[fonts] table: 0x5628065d02e0
[fonts] table: 0x56280c0d1e30<packages/color-fonts>
```

IDK, something is screwy here...

I noticed Libertinus was being replaced with FreeMono, so despite my distaste for Libertinus,[[1]](https://github.com/alerque/libertinus/issues/329) (why can't I stop bringing this up? :man_facepalming:), I extracted Version 6.12 to `~/.local/share/fonts`, and still get exact same crash.

Here's my whole `/usr/share/fonts/truetype/roboto-fontface/roboto-condensed/`: 
* [RobotoC.zip](https://github.com/sile-typesetter/sile/files/5034671/RobotoC.zip)

And <kbd>Gentium Book Basic</kbd>, because why not?: `fc-list|grep 'Gentium Book'|awk -F':' '{print $1}'|xargs zip GentiumBB.zip`: 
* [GentiumBB.zip](https://github.com/sile-typesetter/sile/files/5034682/GentiumBB.zip)

**Comment by alerque** [comment] 2020-08-06 13:10
Don't build the manual by calling SILE yourself, all the exact fonts needed are setup properly if you use the build system:

```console
$ make docs
```

Or if you want just the manual:

```console
$ make documentation/sile.pdf
```

Also the CI system rebuilds the manual for PR's if you want to check the PDF from the artifacts.

All the same it shouldn't have hard crashed like that, I'll look into what the error actually is about.

**Comment by ctrlcctrlv** [comment] 2020-08-06 13:21
@alerque Thanks for the build tip, that does work for me; and is obviously much better than me trying to hunt down the fonts! 😹 

I'll leave this open since hard crashes are obviously bad and stuff. I think I found the problem: we're assuming fonts are going to always have valid PostScript names I think, but this version of Roboto Condensed...doesn't. Its OTF family name is `.\x7f` and its PostScript name is `.`. 😖 

Clearly I'm no expert, but that seems...bad!

**Comment by simoncozens** [comment] 2020-08-07 08:08
The font in your attached zip file parses fine here (and has an OT family name) but is *not* the "Webfont" version referenced above.

```
> ot = SILE.require("core/opentype-parser")
> fontoptions = SILE.font.loadDefaults({filename="RobotoCondensed-Light.ttf"})
> face = SILE.font.cache(fontoptions, SILE.shaper.getFace)
> font = ot.parseFont(face)
> font.names[1].en
{
  "Roboto Condensed",
}
```

Where's the "Webfont" coming from? It's not in any of the files you sent.

**Comment by alerque** [comment] 2020-08-12 08:24
I just used the Roboto font packages & SILE from our PPA on both Bionic and Focal and didn't have any trouble with the manual, the MWE above or the name debugging Simon showed. Interestingly the Roboto Condensed supplied by Ubuntu doesn't have an `en` name key, but it does have `en-US`. Besides issues like that I wasn't able to replicate the trouble initially described at all on either version of Ubuntu.

I'm going to close this for now under the assumption that the initial trouble was a corrupt font file or some other un-repeatable condition that we can't be expected to handle cleanly. If more information turns up, there is a way to reproduce this, and something we can fix I'd be happy to re-evaluate.

**Comment by ctrlcctrlv** [comment] 2020-08-12 08:47
@alerque No idea why you can't replicate the problem, but here are the fonts.

```
$ zip -r RobotoC.zip /usr/share/fonts/truetype/roboto-fontface/roboto-condensed/
updating: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/ (stored 0%)
  adding: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/Roboto-Condensed-RegularItalic.ttf (deflated 47%)
  adding: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/Roboto-Condensed-Regular.ttf (deflated 45%)
  adding: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/Roboto-Condensed-Light.ttf (deflated 47%)
  adding: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/.uuid (stored 0%)
  adding: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/Roboto-Condensed-LightItalic.ttf (deflated 48%)
  adding: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/Roboto-Condensed-Bold.ttf (deflated 45%)
  adding: usr/share/fonts/truetype/roboto-fontface/roboto-condensed/Roboto-Condensed-BoldItalic.ttf (deflated 46%)
```
Fonts: [RobotoC.zip](https://github.com/sile-typesetter/sile/files/5061571/RobotoC.zip)

These don't come from PPA. They come from system package, `fonts-roboto-fontface`.

**Comment by ctrlcctrlv** [comment] 2020-08-12 08:48
```
$ apt info fonts-roboto-fontface
Package: fonts-roboto-fontface
Version: 0.5.0-2
Priority: extra
Section: universe/fonts
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian OpenStack <openstack-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 14.9 MB
Breaks: openstack-dashboard (<< 3:12)
Homepage: https://github.com/choffmeister/roboto-fontface-bower
Download-Size: 3,979 kB
APT-Manual-Installed: yes
APT-Sources: http://us.archive.ubuntu.com/ubuntu focal/universe amd64 Packages
Description: largely geometric, friendly and open curves font
 Roboto has a dual nature. It has a mechanical skeleton and the forms are
 largely geometric. At the same time, the font features friendly and open
 curves. While some grotesks distort their letterforms to force a rigid rhythm,
 Roboto doesn’t compromise, allowing letters to be settled into their natural
 width. This makes for a more natural reading rhythm more commonly found in
 humanist and serif types.
 .
 This is the normal family, which can be used alongside the Roboto Condensed
 family and the Roboto Slab family.
 .
 This package also provides Css, Scss and LESS files to use webfonts from this
 package.
```

**Comment by alerque** [comment] 2020-08-12 09:15
Only SILE in my case comes from our PPA, I'm using apparently the same fonts-roboto-fontface package and version you are (at least for my Focal tests). I still don't have any trouble with the manual (using 0.10.9 sources) or just loading and parsing the font directly.

**Comment by ctrlcctrlv** [comment] 2020-08-12 09:23
@alerque You are looking in directory `/usr/share/fonts/truetype/roboto-fontface/roboto-condensed/` and not `/usr/share/fonts-roboto-fontface/fonts/roboto-condensed/`, yes?

**Comment by ctrlcctrlv** [comment] 2020-08-12 09:25
Because if so I really struggle to understand how it is we're looking at same font.

![image](https://user-images.githubusercontent.com/838783/89998913-fc799480-dc42-11ea-9ad0-c03965653bd1.png)
![image](https://user-images.githubusercontent.com/838783/89998970-0e5b3780-dc43-11ea-8b25-9573de51d33e.png)

Does Fontforge have a bug?

**Comment by alerque** [comment] 2020-08-12 10:02
Ubuntu has not 1, not 2, but 3 different sets of packaging for Roboto, plus a meta package that picks one of the above. 2 of the 3 are okay, the one you have just has a bogus font. I did find the file edition you have, but since I also had other versions they were being picked up first by Fontconfig.

I suggest you install the meta package instead of manually picking which supplier to use. That should net you the hinted version of the font instead of whatever that broken package is even supposed to be.

![image](https://user-images.githubusercontent.com/173595/90002595-848b8880-dc9b-11ea-9d86-54e99c36889e.png)

Loading the font in question into fontforge I get an error on open about the PostScript name being invalid. I don't think I'm really concerned with loading and working with a clearly invalid font. We have enough problems with edge cases in valid font files. @simoncozens might think differently. It's not that I enjoy `sile` crashing, but if we start adding checks to work around clearly invalid input (whether fonts or images or XML or whatever) it's going to take a lot of code to be graceful.

**Comment by ctrlcctrlv** [comment] 2020-08-12 10:10
@alerque Well this issue should be reopened as it's still an issue, even if you think it's a minor one. The input is _not_ invalid, please do not trust FontForge on this. FontForge is wrong; see fontforge/fontforge#3941, the consensus there is clear, I just didn't get around to doing the work of downgrading the error to a warwning.

**Comment by ctrlcctrlv** [comment] 2020-08-12 10:13
There are legitimate reasons some webfonts are named `.\u007f`, the largest one is that it means that there won't be a collision when used in browser, as browsers prefer system fonts always. And there are legitimate reasons to want to use webfonts like this in SILE. 😄

**Comment by alerque** [comment] 2020-08-12 10:29
I don't see the logic in applying the excuse that browsers don't care to SILE.

Fonts generated with the web in mind *could* be used in SILE, but only if they are valid as regular fonts too. Webfonts with invalid PS names? Not so much. The whole point of the restriction on naming schemes in this field is that in order to embed in a PDF you have to have a valid PostScript compatible name. I can see FontForge as a font editor wanting to round-trip even invalid names. I can see webfonts and browsers not caring about this and gracefully ignoring it. But SILE is *primarily* used for generating PDFs. We can't just stuff invalid PS data where PS data is expected.

**Comment by ctrlcctrlv** [comment] 2020-08-12 10:35
All software of note that works with PS names can handle these fonts; if they didn't, very few of the commercial CJK fonts I've seen would work.

**Comment by simoncozens** [comment] 2020-08-12 10:36
If this was a crash in the output routine, it would have something to do with PS font data, and I'd say fine, invalid font, GIGO. But it's a crash in our OpenType parser. *At the very least*, we should gracefully complain about the font file.

**Comment by alerque** [comment] 2020-08-12 10:38
> if they didn't, very few of the commercial CJK fonts I've seen would work

As far as I understand it we're not talking about validating PS here. We don't fail on CJK fonts that have UTF8 in there that doesn't belong. We're failing on a `nil` value where the spec demands a value and we need a value to generate a PDF. No?

**Comment by simoncozens** [comment] 2020-08-12 10:43
No. The color-fonts package opens up the font and reads the COLR table so it knows what colours to use, and calls opentype-parser to do so. That's exploding for some reason when it tries to read the name table. Not even close to PDF generation at this stage.

**Comment by khaledhosny** [comment] 2020-08-12 16:16
> as browsers prefer system fonts always

That is not true, browsers won’t load local fonts unless instructed to do so (i.e. by using `local()` in `@font-face` rule).

**Comment by ctrlcctrlv** [comment] 2020-08-12 16:36
@khaledhosny Really? Has that always been the case? 🤔

**Comment by khaledhosny** [comment] 2020-08-12 16:37
> @khaledhosny Really? Has that always been the case? 🤔

For as long as web fonts were supported by browsers.

**Comment by ctrlcctrlv** [comment] 2020-08-12 16:42
So wait, you're saying that if I have...

```css
@font-face {family: 'Comic Sans', url('./ComicSans.ttf')}
body {font-family 'Comic Sans'}
```

The <kbd>@font-face</kbd> will be preferred over the system Comic Sans?

**Comment by khaledhosny** [comment] 2020-08-12 16:55
Yes. Any way, browsers doesn’t read `name` table of web fonts at all, so it does not matter what is in their, some web fonts ”obfescuters” use this fact to put garbage in `name` table so that fonts are not installable locally.

**Comment by ctrlcctrlv** [comment] 2020-08-12 23:07
Thanks for the explanation @khaledhosny. Of course I had considered obfuscation, but I know that Roboto is open source, so have no idea why Google is doing it...:thinking:...there's no commercial licensing interest in Roboto to protect is there?

**Comment by khaledhosny** [comment] 2020-08-12 23:22
No idea, someone probably used some webfont generator and didn’t give it much thought.

**Closed** 2020-08-13 14:29 UTC
Labels: bug
