### ISSUE TITLE
Improvements to the machine-readable text in the PDF file

### ISSUE THREAD

**Issue by raphCode** [sile-typesetter/sile#1663] opened 2022-12-19 14:13 UTC
I noticed room for improvements in the machine-readable text in the PDF outputs:
- double clicking and dragging usually selects on word boundaries, but in Sile PDFs these boundaries often also appear inside of words where they don't make sense. (Needs Reader support, I believe Google Chrome doesn't do it)
- Selecting and copy-pasting the text eliminates all spaces from the text (Tested with Firefox's PDF viewer)
- Similarly, the selection visually doesn't span the spaces but is interrupted between the words

Both points can be reproduced with a lorem ipsum text (and likely any other document).

This is a low priority issue for me since most PDFs are only viewed or go to printing anyways, but I thought it would be nice to open an issue.

**Comment by ctrlcctrlv** [comment] 2022-12-19 19:48
Closing as duplicate of #494. Thanks for reporting your experience, that issue has some ideas for fixing it :)

**Closed by ctrlcctrlv** 2022-12-19 19:48 UTC

**Comment by raphCode** [comment] 2022-12-19 21:00
Sorry, I searched for similar issues but wasn't able to find that one.
