### ISSUE TITLE
Google mailing list isn't publicly visible

### ISSUE THREAD

**Issue by Andonome** [sile-typesetter/sile#717] opened 2019-11-05 20:18 UTC
The readme says to contact the google mailing list:

https://groups.google.com/forum/#!forum/sile-users

But Google tells me there is no such group, or that the group is closed.

Suggestion: either open the group, or remove the link from the readme.

---

And just in case it's closed, I'll grab this opportunity to firstly say *thanks* - Latex has had me pulling out hair, and I've so far stuck three random SILE functions together and had the results come out perfectly.

Secondly, is there any likelihood of floating images in the future?  Specifically, I need to insert a load of svg images about half the width of the page, and have them automatically determine their own (proportional) height, and make their own decision about raising above their current position or skipping to the next page, without leaving a trail of destruction and whitespace across the rest of the chapter.

**Comment by alerque** [comment] 2019-11-06 04:45
The Google mailing list isn't very active, but it does exist. The link in the README works for me, but I do notice that it's getting redirected to this URL in the end: https://groups.google.com/d/forum/sile-users — perhaps you have some of Google's scripts blocked and aren't getting redirected?

Please feel free to edit the README to fix that link and submit the change as a PR.

----

As for floating images ... sure it's possible but somebody has to write it and there is a _lot_ of work involved in making that even halfway sane. I don't have any plans of tackling it soon, although it has crossed my mind a few times. I'd be happy to help somebody along if they wanted to try to make it happen, but fair warning: that isn't a beginner level task and it is not going to be a fun first contribution. ;-)

**Comment by Andonome** [comment] 2019-11-06 05:06
The link's not working for me in three browsers.  No script is being used - perhaps it's because I'm in Thailand?  If it's working for others who are not signed in, might be time to close the issue (I don't have a VPN to test).

--- 

I've just found lua yesterday, so I'll leave floats for now.

**Comment by DavidLRowe** [comment] 2019-11-06 05:24
I tried the google group link and got:
```
This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.
```

**Comment by alerque** [comment] 2019-11-06 06:33
I am a member, but not any kind of administrator for the list so @simoncozens might have to look into what is up. However it doesn't seem like this is actually a group settings problem because looking at the "about group" link I see this:

![2019-11-06_09-32](https://user-images.githubusercontent.com/173595/68273784-6e9bc800-0078-11ea-91ec-8335586d80c6.png)

**Comment by alerque** [comment] 2019-11-06 06:40
I just checked it from a browser that is not logged into my Google account and was able to view the list as a guest.

If there is not some sort of regional restriction on Google Groups then I don't know what to say. Are you guys able to get to other groups anonymously?

**Comment by alerque** [comment] 2019-11-06 07:09
I created a PR for updating the links to the permalink format, but there is still something weird going on. I can't replicate your issues with getting to the EN group, but trying to reach the JA group gives me a 418 error:

> You do not have permission to access this content. (\#418)

I think @simoncozens will have to sort that one out.

**Comment by simoncozens** [comment] 2019-11-12 14:33
To be honest I think the Google mailing list never really took off and if people have questions they more likely ask them here. Which is fine. So I suggest just getting rid of references to it.

**Comment by ctrlcctrlv** [comment] 2020-07-29 10:12
@PapistPenguin just noticed this too (#989). I noticed it before, including very sadly, the Japanese mailing list also not existing, which I was excited to join, as I was hoping for dank `tate` tips. :cry:

It should be removed, don't entice me like that! :wink:

**Comment by alerque** [comment] 2020-07-29 22:31
I don't know what the deal with the JP list is, @simoncozens will have to answer for that. I can't get to it, but some people could even when I couldn't so something is weird. If it's really dead then I agree we should just remove the reference.

That being said, the English list as linked in the README seems to be fully functional. I just checked it and the link seems alright. @PapistPenguin can you confirm what URL you were headed too?

**Comment by ctrlcctrlv** [comment] 2020-07-29 22:35
@alerque This is what I see.

![image](https://user-images.githubusercontent.com/838783/88860630-0a460900-d1b1-11ea-9394-5e7c279ba168.png)

> This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the Owner of the group and ask them to give you access.

I imagine @PapistPenguin sees similar.

**Comment by alerque** [comment] 2020-07-29 22:39
I think both groups must be set to some kind of "only members can view" mode. Since I happen to be part of the EN group I can see that but not the JP one. I don't have admin access to either to poke around the settings, (Simon maybe you can add me) but I can confirm the "logged into my Google account" view is fine and in a private browser window without my login it's a dead link.

**Comment by alerque** [comment] 2023-03-26 11:46
This isn't actually fixed. The EN one might be, but the JA group is still members-only.

The fix for this *may* be to just drop the link from the README, but until somebody with any knowledge of or access to the JA group steps in to say what the deal is this should stay open to track it.

**Comment by Omikhleia** [comment] 2023-03-26 12:28
Ah indeed. I hadn't noticed the JA mailing list.

> but until somebody with any knowledge of or access to the JA group steps in to say what the deal is this should stay open to track it.

I suggest we take action in 1 month = kill the link in the README unless "someone" steps in to solve it.

**Comment by ctrlcctrlv** [comment] 2023-03-27 07:54
I can volunteer to manage the Japanese list if that's what is needed. While I speak it far worse than Simon does, I have considerably more time.

もし必要であれば、私がボランティアで日本語リストを管理することができます。サイモンより遥かに下手だけど、時間はかなりあるんだ。

**Comment by alerque** [comment] 2023-03-28 19:10
@Omikhleia One place this should be asked before we impose a time limit is the actual Japanese list itself. I don't have access to do so, but at one point there were quite a few users there. Those are the folks that should be polled.

Just FYI at one point there was even a complete SILE manual translated to Japanese (when it was 80-90 pages if I recall). I don't know if there is still lots of active use in an isolated subculture there, but at one time at least there was. Until we poll somebody from that group I don't think we should impose time limits on erasing notes about their existence.

**Closed** 2023-10-06 19:57 UTC
Labels: documentation
