### ISSUE TITLE
Manual §1.3 layout error

### ISSUE THREAD

**Issue by jamadagni** [sile-typesetter/sile#560] opened 2019-03-24 05:10 UTC
Following display of §1.3 of manual:

version 0.9.4 from website:

![correct-display-0 9 4](https://user-images.githubusercontent.com/948170/54875221-ca367f80-4e20-11e9-8f7e-3f55803b5849.png)

current master from https://raw.githubusercontent.com/simoncozens/sile/master/documentation/sile.pdf:

![incorrect-display-master](https://user-images.githubusercontent.com/948170/54875222-ca367f80-4e20-11e9-9008-dae73a2e22b9.png)

There doesn't seem to be a problem with the .sil file so maybe it's with the current master version of the typesetter?

**Comment by alerque** [comment] 2019-03-24 05:53
This is almost certainly a problem in the typesetter itself. I also think it existed pre 0.9.4, it is just chance and very minor metrics that kept it from manifesting. The issue has something to do with the frame breaker that serves to wrap images like that. Sometimes the first paragraph following the break does not get terminated properly. I have seen similar problems with drop-caps at the start of chapters. Sometimes fudging them around a few points higher or lower on the page makes the problem go away. I haven't been able to produce a MWE yet.

**Comment by OlivierNicole** [comment] 2019-05-25 17:21
This is not the only issue. If we are talking about [this document](http://sile-typesetter.org/images/sile-0.9.4.pdf), the typesetting is messed up mid-document (from page 36 onwards), with hyphenation and typesetting no longer working.

**Comment by alerque** [comment] 2021-06-16 20:05
This is a duplicate of #491.

**Closed by alerque** 2021-06-16 20:05 UTC
Labels: bug, needs MWE
