### ISSUE TITLE
Please add a way for me to tell SILE to automatically run itself twice if it sees that the TOC needs changing at end of document

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1028] opened 2020-08-14 09:34 UTC

**Comment by alerque** [comment] 2020-08-14 09:42
Duplicate of #230. I've taken several stabs at it already but haven't gotten anything contributable yet.

See Makefile.am or CaSILE for a way to do this in a build system.

**Closed by alerque** 2020-08-14 09:42 UTC
