### ISSUE TITLE
SILE comes up with really ugly strings for fonts with OpenType substitutions

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1145] opened 2021-02-16 03:13 UTC
Fonts like my latest release, [FRB American Cursive](https://raw.githubusercontent.com/ctrlcctrlv/FRBAmericanCursive/main/specimens/FRBAmericanCursive-specimen.pdf), rely on OpenType substitutions for proper display. Without a correct shaping engine, this font would not work at all.

SILE has one, but it seems when it's time to write the PDF, it forgets the original characters input by user, and shows instead:

```
9İēs  qƊĶ_ļs  bŮŐȥŇƀ  fŐȨƀ  jƊŃŚŲƀ  oȢĒůƀ  tıēs  lHȰȬƀ  dŐĤƀ.
```

For:

```
The quick brown fox jumps over the lazy dog.
```

I have seen other software not do this (ConteXt), and write correct PDF, so I consider it a SILE bug.

**Comment by simoncozens** [comment] 2021-02-16 10:20
Duplicate of #494. And yes, I need this too, because I can't copy-paste my Arabic test files.

**Closed** 2021-02-16 12:44 UTC
Labels: duplicate

**Comment by ctrlcctrlv** [comment] 2021-02-16 13:31
Ah, I'm sorry for creating a duplicate. I didn't know the name of the tag in the PDF standard that was causing some documents to look right and others to not: didn't know what to search. Thank you.

**Comment by alerque** [comment] 2021-02-16 13:41
No worries at all, when duplicates start cropping up that's a useful indicator we've under-prioritized an issue ;-) I've self-reported issues myself only to find I already reported them. In those cases I don't even have the excuse I didn't know the name of something!
