### ISSUE TITLE
Provide a compelling show-case document

### ISSUE THREAD

**Issue by the42** [sile-typesetter/sile#343] opened 2016-07-21 08:57 UTC
The provided what's possible with Sile document https://github.com/simoncozens/sile/blob/master/examples/showoff.pdf is not compelling/convincing enough. Take for example http://wiki.contextgarden.net/Sample_documents. I am not talking about the amount of documentation there but about the width and features possible. For instance, the show-off document lacks tables or enumerations as a starter.

**Comment by akavel** [comment] 2016-10-06 15:43
I found some of the stuff at the end of the FOSDEM presentation quite powerful, especially with the commentary. The most eye-catching of those was I think the Bible page &mdash; in my view it's kinda iconic for SILE, its power and maturity. I wonder sometimes why it's not more prominently displayed on the SILE website, to make a solid first impression on the visitors.

**Comment by the42** [comment] 2016-10-13 16:55
But for heavens sake (pun intended) do not use the bible as "the" default show-off document, go rather for something innocuous, showing a TOC, headers, sections, footnotes, enumerations, utf8, bidi support and how to include external material (pictures). That would suffice.

**Comment by Omikhleia** [comment] 2024-10-19 22:03
This issue did not received any activity for several years.
I am closing it, but please feel free to re-open a dedicated issue if a different approach should be discussed.

Aside note: the [Wiki](https://github.com/sile-typesetter/sile/wiki/Works-composed-with-SILE) now has several pointers to books made with SILE, including a few show-cases. The issue is very general, and might not be addressed in a foreseeable future, but additionally
 - Enumerations (lists) made it to the core distribution some time ago and are documented in the user manual
 - There's a least a 3rd-party solution available for tables.

**Closed by Omikhleia** 2024-10-19 22:03 UTC
Labels: documentation
