### ISSUE TITLE
Does not work with Fira Math.

### ISSUE THREAD

**Issue by kindaro** [sile-typesetter/sile#1577] opened 2022-10-04 18:20 UTC
## see for yourself

* On Arch Linux, build and Install `otf-firamath` from AUR.
* Downloaded the example called `math.sil` from the official site.
* Apply this edit:

  ```diff
  --- math.sil	2022-10-04 20:44:33.699784267 +0300
  +++ math-fira.sil	2022-10-04 20:45:15.259782736 +0300
  @@ -2,7 +2,7 @@
  \neverindent
  \script[src=packages/math]
  \font[family=Libertinus Serif,size=14]
  -\set[parameter=math.font.family,value=Libertinus Math]
  +\set[parameter=math.font.family,value=Fira Math]
  \set[parameter=math.font.size,value=14]
  \define[command=bold]{\font[weight=800]{\process}}
  \define[command=bold]{\font[weight=800]{\process}}
  ```

* Run `sile math-fira.sil`

## outcome that I hoped for

* The command exits with 0.
* A file `math-fira.pdf` appears with some mathematical formulæ inside.

## outcome that happens

* The command exits with 1.
* The following error appears:

      SILE v0.14.3 (Lua 5.4)
      <math-fira.sil> as sil

      ! Unexpected Lua error

      error summary:
        Processing at: math-fira.sil:11:18: in \math
        Using code at: /usr/share/sile/packages/math/base-elements.lua:117: bad argument #1 to 'for iterator' (table expected, got nil)

      Run with --traceback for more detailed trace leading up to errors.

* Furthermore, the following error appears when running `sile math-fira.sil --traceback` as suggested by the error message above.

      SILE v0.14.3 (Lua 5.4)
      <math-fira.sil> as sil

      ! Unexpected Lua error

      stack traceback:
        [C]: in function 'next'
        /usr/share/sile/packages/math/base-elements.lua:117: in function </usr/share/sile/packages/math/base-elements.lua:95>
        (...tail calls...)
        /usr/share/sile/packages/math/base-elements.lua:271: in method 'getScaleDown'
        /usr/share/sile/packages/math/base-elements.lua:849: in method 'shape'
        /usr/share/sile/packages/math/base-elements.lua:299: in method 'shapeTree'
        /usr/share/sile/packages/math/base-elements.lua:297: in method 'shapeTree'
        /usr/share/sile/packages/math/base-elements.lua:297: in method 'shapeTree'
        /usr/share/sile/packages/math/typesetter.lua:142: in method 'handleMath'
        /usr/share/sile/packages/math/init.lua:69: in field '?'
        /usr/share/sile/core/sile.lua:363: in function 'core.sile.call'
        /usr/share/sile/core/sile.lua:224: in function 'core.sile.process'
        /usr/share/sile/classes/base.lua:306: in field '?'
        /usr/share/sile/core/sile.lua:363: in function 'core.sile.call'
        /usr/share/sile/core/sile.lua:224: in function 'core.sile.process'
        (...tail calls...)
        /usr/share/sile/core/sile.lua:288: in function 'core.sile.processString'
        /usr/share/sile/core/sile.lua:319: in function 'core.sile.processFile'
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/bin/sile:115: in main chunk
        [C]: in ?

      error summary:
        Processing at: math-fira.sil:11:18: in \math
        Using code at: /usr/share/sile/packages/math/base-elements.lua:117: bad argument #1 to 'for iterator' (table expected, got nil)

* No PDF files appear.

## discussion

* The error that appears when the font named in `math.font.family,value` is not installed is different — it clearly says that the font is not found. This suggests that `sile` indeed can find the font `Fira Math`.
* I tried some other fonts, such as `XITS Math` and `Asana Math` — they all work so far.

## version

    % sile --version
    SILE v0.14.3 (Lua 5.4)

**Comment by Omikhleia** [comment] 2022-10-04 21:15
Perhaps Fira Math doesn't have math italic corrections?

**Comment by alerque** [comment] 2022-10-05 04:21
Great bug report, thanks sor the detail. It does look like we're expecting something in the font that isn't there. The question is what and why. If we need it we should check explicitly and throw a more usable error. If we can work around it maybe just a warning…or nothing.

**Comment by ctrlcctrlv** [comment] 2022-10-11 02:15
The font has a proper MATH table and plenty of italic corrections. I think the parser is at fault, not the font.

**Comment by alerque** [comment] 2022-11-04 12:58
Just as some points of reference while looking into this:

1. Pretending there is an empty table of italic corrections works otherwise with Fira Math, it's just the no-results issue tripping us up. I can easily skip it, but since Fredrick says the font looks fine I'll dig into why it's not parsing.

2. Some other fonts work.

    - ✓ STIX Two Math
	- ✓ Latin Modern Math
	- ✓ DejaVu Math TeX Gyre

3. Some other fonts don't work (but for other reasons?).
	- 🗴 Noto Sans Math

**Comment by alerque** [comment] 2022-11-04 14:58
Just for grins, I tried a 0.3.x series Fira Math release in case the 0.4.x beta used above was a problem. Same issue.

Looking at FiraMath tables dumped with `ttx` there is definitely an `MathItalicsCorrectionInfo` table and structurally is seems about the same as other fonts that work — at least the dumped version. Our parser actually sorting through the binary font looks pretty straightforward, but for some reason it's coming back with a nil value for the offset where the data should be found.

I'm a little out of my depth here. I can't help but thinking we should probably be using some font loader library rather than parsing through the binary ourselves with *vstruct*, but fixing that is probably out of scope for this issue. In the mean time I think I'm probably going to have to bump this to another release cycle.

**Comment by Omikhleia** [comment] 2023-01-01 19:15
Weird...
I had no problem with SILE v0.14.7 (Lua 5.4) run from docker:
- with Fira Math 0.3.4 (`FiraMath-Regular.otf` file taken from https://github.com/firamath/firamath/releases). 
- with Fira Math 0.4-beta-3 (_idem_).

The page was generated with all formulas.
My SILE v0.14.7 (Lua 5.4) is a freshly rebuilt docker image (based on the default docker file -- i.e. ArchLinux-based), just modified to included additional fonts and my own packages installed via luarocks after the build steps, as well as a few additional binaries such as Inkscape, GhostScript and GraphicsMagick for "converters")...

Nothing too fancy, but anyway, I then just also tried using standard-distribution docker images, incl. the one from the report:
- `docker run -it --volume "$(pwd):/data" --user "$(id -u):$(id -g)" siletypesetter/sile:v0.14.3 math.sil`
- Likewise with 0.14.6.

With the SILE document now modified as follows to refer to the font by filename:
```
\set[parameter=math.font.family,value=Fira Math]% modified
\set[parameter=math.font.filename,value=./FiraMath-Regular.otf]% modified additional
```

The font file there was 0.4-beta-3, and I got no error either, with the expected output...

So I am unsure what the differences from your setups might be, @kindaro and @alerque, but I couldn't reproduce the problem.

**Comment by alerque** [comment] 2023-01-02 11:48
@Omikhleia You are testing a different MWE than we are, but the difference is quite interesting. I can confirm using `font.filename` instead of `font.family` for the loader bypasses whatever this bug is and does seem to render formulas properly even with Fira Math.

**Comment by alerque** [comment] 2023-01-02 12:44
Armed with that bit of trivia, I've determined that setting `font.family` is actually attempting to load `FiraMath-Book.otf` instead of `FiraMath-Regular.otf`.

**Comment by alerque** [comment] 2023-01-02 13:22
I've got a fix for this queued up. We were not defaulting style & weight values for math fonts to sane values like we were for the regular font loader. Fira has a few more things available and `fontconfig` doesn't default to the expected values. Even `fc-match "Fira Math"` will return the Book style instead of the Regular style like SILE was presuming would happen. That face is a companion font with a different purpose from the main math font.

**Closed** 2023-01-25 12:13 UTC
Labels: bug, packages
