### ISSUE TITLE
Luarocks and SILE's own dependencies?

### ISSUE THREAD

**Issue by Omikhleia** [sile-typesetter/sile#2118] opened 2024-09-28 08:39 UTC
When I want to quickly test or use a new SILE setup, I use a Docker file such as (simplified)
```
FROM docker.io/library/archlinux:base
RUN pacman --needed --noconfirm -Syuu
RUN pacman --noconfirm -S luarocks git
RUN pacman --noconfirm -S sile
RUN sile -V
RUN v=$(sile -q -e 'print(SILE.lua_version); os.exit()'); echo $v > /LVER
RUN luarocks list --lua-version $(cat /LVER)
# Additional stuff goes here (ex. extra tooling, fonts, and my own modules)
WORKDIR /data
ENTRYPOINT ["sile"]
```

If I want everything new, I clear my docker stuff, and rebuild a fresh image with, say: `docker build --progress plain -f build/Dockerfile . -t sile-20240928` 

My question is the following: **what can I expect from the `luarocks list` step?**

If I do (as above) the luarocks/git install steps _before_ sile, then it shows a list of SILE-related dependencies: cassowary, cldr, fluent, linenoise, loadkit, lua_cliargs, luaepnf, luaexpat, luarepl, luasec, luasocket, luautf8, penlight, vstruct.
  - If the order is inverted, the list is empty (so it might have to do with luarocks being on the system?)
  - Anyhow, it doesn't show _all_ Lua libraries that SILE has, notably *lpeg* and *zlib* (for the ones I noticed)

The latter point is troubling, as my additional modules (or one of their dependencies) might want them.
  - It will then fail, as they require a build toolchain[^1] and this image doesn't have build-essentials installed...
  - Of course, the latter could be added... though the idea was to keep with a "small" setup (well, not really trimmed-down here, admittedly, the arch base is not that small... But I never know what stuff such as Ghostscript, Inkscape, etc. might need, so heh...)
  - But anyway, it then means that it will needlessly recompile something SILE actually _already_ comes with, and I'm not even sure which one is then used...
  - (Since I went for a fresh setup here, I don't really care[^2] and this is quite theoretical:) If I later add additional stuff at the end of my Dockerfile without clearing any cache, I might end up with a different version than SILE had (?)

[^1]: For instance:
      ```
      Installing https://luarocks.org/luajson-1.3.4-1.src.rock
      Missing dependencies for luajson 1.3.4-1:
         lpeg >= 0.8.1 (not installed)
      luajson 1.3.4-1 depends on lua >= 5.1 (5.1-1 provided by VM: success)
      luajson 1.3.4-1 depends on lpeg >= 0.8.1 (not installed)
      Installing https://luarocks.org/lpeg-1.1.0-2.src.rock
      lpeg 1.1.0-2 depends on lua >= 5.1 (5.1-1 provided by VM: success)
      gcc -O2 -fPIC -I/usr/include/lua5.1 -c lpcap.c -o lpcap.o
      sh: line 1: gcc: command not found
      ```

[^2]: And it's not as if Lua lpeg and zlib had frequent releases! :rabbit:

**Comment by alerque** [comment] 2024-09-28 10:15
First a couple of usage notes on Docker that you might find useful:

```dockerfile
FROM docker.io/library/archlinux:base

# added cleanup of pacman database and cache so layer size stays small at each step
RUN pacman --noconfirm -Syuq && yes | pacman -Sccq

# moved --needed flag to the installations, not the system refresh
RUN pacman --needed --noconfirm -S luarocks git sile && yes | pacman -Sccq

RUN sile -V

# skipped variable assignment and wrapping just to write a value to a file
RUN sile -q -e 'print(SILE.lua_version); os.exit()' > /tmp/LVER

# setup LuaRocks to default to the right lua version to match SILE
RUN luarocks config lua_version $(cat /tmp/LVER) && \
    luarocks config lua_interpreter luajit && \
    luarocks config variables.LUA "$(command -v luajit)"

# Note --lua-version is no longer needed for all future use in this container
RUN luarocks list

WORKDIR /data
ENTRYPOINT ["sile"]
```

> * If the order is inverted, the list is empty (so it might have to do with luarocks being on the system?)

Yikes! This is an Arch Linux bug. Whet it installs lua modules it just installs them where they go, the with a post-install hook *if* luarocks is available it regenerates the system manifest so that luarocks known what is available where. I guess if you install packages before luarocks is available, that hook doesn't get triggered. I suppose this could be fixed by making sure the hook runs when luarocks installs, not just when some other lua module gets installed later.

> Anyhow, it doesn't show all Lua libraries that SILE has, notably lpeg and zlib (for the ones I noticed)

More Arch package bugs here. Triggering the luarocks manifest update hook requires packages to install the appropriate rock meta data. The `lua51-lpeg` package at least is not doing this, there is no meta data in the package (`pacman -Ql lua51-lpeg`).

I'll go file Arch Linux bugs (and maybe just fix them).

**Comment by alerque** [comment] 2024-09-28 11:15
This should fix the LuaRocks issue: https://gitlab.archlinux.org/archlinux/packaging/packages/luarocks/-/merge_requests/2

Next up, lpeg & zlib. It looks like those are using some hand rolled installation instead of a `luarocks install`, hence they have no meta data.

**Comment by alerque** [comment] 2024-09-28 11:47
This should fix the LPEG package: https://gitlab.archlinux.org/archlinux/packaging/packages/lpeg/-/merge_requests/1

**Comment by alerque** [comment] 2024-09-28 12:16
This should fix the ZLIB package: https://gitlab.archlinux.org/archlinux/packaging/packages/lua-zlib/-/merge_requests/1

If there are other Arch packages that don't play nice and report themselves as available on the system using `luarocks list`, feel free to report those as packaging bugs. I am not the named maintainer for all of them but I can still probably get them fixed.

**Closed** 2024-09-28 12:17 UTC
Labels: question, Not My Bug

**Comment by alerque** [comment] 2024-09-28 12:34
The above three are all pushed to `[extra-testing]`. When mirrors update I expect this Dockerfile to demonstrate that the `luarocks list` works after installing luarocks but without needing to re-install any actual rocks to get a manifest. I also expect it to show lpeg and zlip rocks. Note this is not optimized for layer size or anything like that, just cobbled together

```dockerfile
FROM docker.io/library/archlinux:base

RUN pacman --noconfirm -Syuq

RUN pacman --noconfirm -S sile
RUN pacman --noconfirm -U https://archlinux.org/packages/extra-testing/x86_64/lua51-{lpeg,zlib}/download/

RUN pacman --noconfirm -U https://archlinux.org/packages/extra-testing/any/luarocks/download/

RUN luarocks --lua-version 5.1 list

RUN pacman --noconfirm -S lua51-cassowary

RUN luarocks --lua-version 5.1 list
```

**Comment by alerque** [comment] 2024-09-28 12:51
I just gave `compat53` packages on Arch a similar overhaul so it has a manifest now (in testing).

**Comment by Omikhleia** [comment] 2024-09-28 13:21
Wow, you rock, as always :+1:

**Comment by alerque** [comment] 2024-09-28 13:28
Pacman 7 seems to have a regression that has broken the expected function of my test case above, [reported upstream here](https://gitlab.archlinux.org/pacman/pacman/-/issues/197). That one is above my pay grade to fix directly.

Testing with Pacman 6 instead the fixed I made to packages do seem to have the effect of showing a proper result with `luarocks list` even when installing luarocks after the other packages. I'm moving on to other issues unless there are reports of more Lua packages that don't install metadata on Arch.

```dockerfile
FROM archlinux:base-20240818.0.255804

RUN pacman --noconfirm -Syq

RUN pacman --noconfirm -Sq sile
RUN pacman --noconfirm -U https://archlinux.org/packages/extra-testing/x86_64/lua51-{lpeg,zlib,compat53}/download/

RUN pacman --noconfirm -U https://archlinux.org/packages/extra-testing/any/luarocks/download/

RUN luarocks --lua-version 5.1 list

RUN pacman --noconfirm -S lua51-cassowary

RUN luarocks --lua-version 5.1 list
```
