### ISSUE TITLE
Pullquote in a footnote has unnecessary space around it

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#1683] opened 2023-01-03 02:18 UTC
# Without ctrlcctrlv#1
![image](https://user-images.githubusercontent.com/838783/210292390-ae12afb1-7c8b-40ef-a1a5-e2980cbe865b.png)

# With ctrlcctrlv#1
![image](https://user-images.githubusercontent.com/838783/210291796-d822213d-838b-441b-baca-450510def557.png)

I make the issue as I'm very unsure about how hacky ctrlcctrlv#1 is. But works on my machine™.

**Comment by Omikhleia** [comment] 2023-01-03 08:42
Doesn't seem to be a bug to me. Pullquotes plays with left and right skips and is ugly in "inline" content anyway!

**Comment by alerque** [comment] 2023-01-03 11:19
My take is similar to @Omikhleia's: The package was not intended for use in inline content, only as a block. We could use a good quote package to handle nested quoting styles, but pullquotes seem to be block (vertical-mode in SILE parlance) level content by definition. Hacking it up for a specific use case is totally fine (one way to do that is to subclass the package module in the document itself), but I don't plan to accommodate inline usage by default. A forced `typesetter:leaveHmode()` does seem to be in order.

**Comment by Omikhleia** [comment] 2023-01-03 19:24
@ctrlcctrlv 
- On the second example, the indented internal alignments from the pullquote are no longer respected; the opening quote is off, and the closing quote is in the margin... It's rather worse than better, typographically speaking ;-)
- If there was some content in the footnote, a `\par` and then the pullquote (i.e. the pullquote is but a part of the note), it was previously (kind of) correct:
   ![image](https://user-images.githubusercontent.com/18075640/210423370-37161a81-40c9-4eb0-b702-c41211b289f2.png)
  The proposed "solution "would break that... severely.
- Regarding how hacky is the proposed change: checking (via modified stack traces) if the pullquote is in a footnote seems plain wrong to me. The footnote is not the issue (see below). It's not a general solution, anyhow, and it would still behave "weirdly" in any similar situation, or with documents that use other type of commands for footnotes, sidenotes of different kind, etc.

The issue is not really the footnote:
- First of all, it's the fact that the pullquote stays in horizontal mode, where previous content was already (here the footnote marker and indent, but that would be true for anything else). It _could_ enforce leaving it (you'll end up with a blank line then, however).
- There's also the fact that the pullquote indents don't take care of existing indents (= this has several consequences, notably that nested pullquotes are not really possible).

What one _could_ more logically want is something as follows, IMHO:
![image](https://user-images.githubusercontent.com/18075640/210424924-85434248-45ea-4666-a17f-d2d5c08e5f9e.png)

I don't much like these pullquotes in footnotes, but at least it looks better this way, at least to my taste. It's not trivial code, though.

**Comment by ctrlcctrlv** [comment] 2023-01-04 08:53
@Omikhleia Thank you for the detailed reply. I clearly don't know enough about how SILE/TeX is implemented, honestly I should just do some reading about what "horizontal mode" and "vertical mode" even means.

I like pullquotes in footnotes, but maybe I'm strange. I've done it in Japanese typesetting before too.

**Comment by Omikhleia** [comment] 2023-01-04 10:39
>  I clearly don't know enough about how SILE/TeX is implemented, honestly I should just do some reading about what "horizontal mode" and "vertical mode" even means.

You can regard this (more or less) as "inline" (horizontal nodes) content vs. "block" (or lines, vertical skips, etc.) content. Text nodes, hboxe's etc. are pushed in horizontal mode (in a queue). When switching from horizontal mode to vertical modes, in most cases (I am simplifying), the typesetter collects the horizontal content so far and involve the line break algorithm to break it into paragraph lines (into another queue of vertical boxes). One leaves horizontal mode by invoking `SILE.typesetter.leaveHmode()` or the `\par` command (with some subtleties here, they are not strictly equivalent, the latter takes care of paragraph skips, etc.).

**Closed** 2023-04-11 09:08 UTC
Labels: bug
