### ISSUE TITLE
math: Equation disappears when immediately preceded by a line break

### ISSUE THREAD

**Issue by matteodelabre** [sile-typesetter/sile#1495] opened 2022-07-25 03:09 UTC
When the following document is compiled, the second equation (`y`) is not shown.

```tex
\begin{document}
    \script[src=packages/math]
    \math{x}\cr\math{y}
\end{document}
```

Adding just a single non-whitespace character between `\cr` and `\math{y}` is enough to make it display the `y`. This also happens with the `\mathml` command.

I’m using the latest commit from master (c7db5d5b3c5c6756ffe7e923ea3b938148167b2b). Here’s the output from `--debug=versions`:

```console
$ ./sile --debug=versions ./wraptest.sil
SILE v0.13.3.r182-gc7db5d5-dirty (Lua 5.4)
<./wraptest.sil> as sil
[1]
Harfbuzz version: 4.4.1
Shapers enabled: graphite2, ot, fallback
ICU support enabled

Fonts used:
/usr/share/fonts/libertinus/LibertinusMath-Regular.otf:0        Version 7.040;RELEASE
/usr/share/fonts/gentium/GentiumPlus-Regular.ttf:0      Version 6.101
```

**Comment by OlivierNicole** [comment] 2022-07-28 12:39
What is `\cr` supposed to do?

**Comment by alerque** [comment] 2022-07-28 12:48
It is similar to `\break` in that it adds a line break, but it also adds an `\hfill` to the line first. Basically it allows line breaks in justified paragraphs. I'm not sure it is the best tool for the job here since switching to a ragged environment would probably be better, but either way the equation getting dropped is not good.

**Comment by matteodelabre** [comment] 2022-07-28 13:08
The bug also happens when using just `\break`, so it doesn’t seem to be linked to the `hfill`.

**Comment by alerque** [comment] 2022-07-28 13:10
Yes, and `\break` just adds a `\penalty` of a big value. I lowered the value a bit and the bug went away. I'm guessing somehow math stuff is getting marked as discardable after breaks, but I didn't actually find the root cause yet (or I would have fixed it!).

**Comment by Omikhleia** [comment] 2022-07-28 14:23
If this may help, this seems to be part of the issue, perhaps!
- Using box (not an hbox or vbox)
- Not invoking the parent class init
```
 elements.mbox = pl.class({
-  _base = nodefactory.box,
+  _base = nodefactory.hbox,
   _type = "Mbox",
   __tostring = function (s) return s.type end,
   _init = function(self)
+    nodefactory.box._init(self)
```

**Comment by Omikhleia** [comment] 2022-07-28 14:50
N.B. In SILE 0.12.5, I could get the correct output with:
```
248c248
<   _base = nodefactory.box,
---
>   _base = nodefactory.hbox,
251a252
>     nodefactory.hbox._init(self)

In SILE 0.13.2, I had to use `nodefactory.box._init(self)`, or `./packages/math/base-elements.lua:251: attempt to call a nil value (field '_init')`

This said, I have not idea whether a mbox ought to be an hbox (except that having it a box, the base class, is problematic has as a "special" type and was surely not intended to be used directly (`is_hbox`/`is_vbox`, and even `is_box` evaluate to false, and these are used afterwards in plenty of line and page breaking things ;). I have no idea either the super-class init has to differ between 0.12.5 and 0.13+ (except that it was probably missing anyway).

**Comment by alerque** [comment] 2022-07-28 15:12
This syntax of specifying a parent class is really hard to debug and itself quite buggy. I've converted almost everything else to the more understandable and reliable alternative syntax, but this should be updated too.

Instead of:

```lua
elements.mbox = pl.class({
  _base = nodefactory.box,
  _init = function()
    nodefactory.box._init(self)
...
```

use something like:

```
elements.mbox = pl.class(nodefactory.box)
function elements.mbox:_init ()
   nodefactory.box._init(self)
...
```

**Comment by matteodelabre** [comment] 2022-08-02 01:26
I think I’ve found the place that actually discards the node. `breakpointsToLines()` breaks the node list into lines according to previously computed break points, and skips lines that don’t contain any node that `is_box` or `is_discretionary`:

https://github.com/sile-typesetter/sile/blob/7925d45257d2fb228d1c569eabeb5f7ade35d9ef/typesetters/base.lua#L656-L663

(By the way, is it intentional that `linestart` is initialized to 0 and not 1 at the start of this function?)

So @Omikhleia is correct, it seems that `mbox` should be a marked as a box node to fix this bug.

**Comment by alerque** [comment] 2022-08-02 05:41
> So @Omikhleia is correct, it seems that `mbox` should be a marked as a box node to fix this bug.

...or the existing conditional needs to be fixed. It sounds like we aren't asking it the right question there. There should probably be some other single node attribute that answers that question in such a way that each node type could decide to play or not.

**Comment by Omikhleia** [comment] 2022-08-02 08:34
@matteodelabre 
> So @Omikhleia is correct, it seems that mbox should be a marked as a box node to fix this bug.

What I am hinting at is that it should probably be an hbox (horizontal) _or_ a **vbox** (vertical). I don't know the math stuff, but reading a bit further, it seems to be a horizontal box is probably intended here.

The nodefactory.box "base/abstract" class is not intended to be used directly: AFAIK, there are not case of it except here in this math-related mbox element. 

(N.B. The line you quote is one place where the "is_box" check is used, there are a few others too (in the alternate first-fit line breaking algorithm, in the nnode management, etc.).

**Comment by Omikhleia** [comment] 2022-08-02 08:53
Additionaly, regarding calling the parent class initializer, this seems to be better than my initial proposal
```
 elements.mbox = pl.class({
-  _base = nodefactory.box,
+  _base = nodefactory.hbox,
   _type = "Mbox",
   __tostring = function (s) return s.type end,
   _init = function(self)
+    self:super()
     self.options = {}
     self.children = {} -- The child nodes
     self.relX = SILE.length(0) -- x position relative to its parent box
```
(Yet a better rewrite would additionally follow @alerque 's [comment](https://github.com/sile-typesetter/sile/issues/1495#issuecomment-1198291933) and split these things in standalone methods and fields)

**Comment by matteodelabre** [comment] 2022-08-02 14:39
> ...or the existing conditional needs to be fixed. It sounds like we aren't asking it the right question there. There should probably be some other single node attribute that answers that question in such a way that each node type could decide to play or not.

@alerque That’s a good point. Some special nodes may need to be kept even on empty lines. For example, info nodes are affected by the same issue, so this code:

```tex
\begin{document}
  \script[src=packages/infonode]
  \begin{script}
    SILE.documentState.documentClass:registerHook("endpage", function ()
      if SILE.scratch.info.thispage.test then
        print("info nodes: " .. #SILE.scratch.info.thispage.test)
      else
        print("info nodes: none")
      end
    end)
  \end{script}

  a\break\info[category="test", value="123"]
\end{document}
```

will print `info nodes: none`.

> (N.B. The line you quote is one place where the "is_box" check is used, there are a few others too (in the alternate first-fit line breaking algorithm, in the nnode management, etc.).

@Omikhleia Sure, but disabling that line *does* fix the issue reported here, so it seemed relevant to me to mention it.

**Comment by Omikhleia** [comment] 2022-08-02 15:37
@matteodelabre Good catch for the info node issue. A bit different, though: it inherits nodefactory.hbox, but overrides the type. What is the reason for it do be tagged "special"? I do have kind of a feeling, not that the line breaking logic is broken, but rather that some nodes are wrongly typed or derived (e.g. see also #1492, which sums up at a similar question: what is the reason for it to be tagged as discardable)...

**Comment by Omikhleia** [comment] 2022-08-02 15:51
I'll rephrase my feeling above: the line-breaking test above might be a bit wrong, as are already a lot of subtle things in the typesetter does (e.g. #1362 #1358 and friends). On the other hand, it also reveals some other things are possibly a bit wrong too, or (at best) have unexplained weird choices (e.g. the mbox, the info node, the insertion nodes).

**Comment by matteodelabre** [comment] 2022-08-04 03:20
@Omikhleia Switching the class base to `hbox` and calling the parent constructor as you suggested also fixes the line breaking in paragraphs that contain inline math. See the following example from the SILE book:

*(before)*
![Screenshot from 2022-08-03 23-10-49](https://user-images.githubusercontent.com/1370040/182755382-cfecfcd3-bf4f-4c2c-82d1-9840e07a2132.png)

*(after)*
![Screenshot from 2022-08-03 23-09-53](https://user-images.githubusercontent.com/1370040/182755385-4d669da5-840e-40c1-b634-adf4189d669a.png)

**Comment by matteodelabre** [comment] 2022-08-04 12:25
Sourds good. I'll prepare a PR for this.

**Comment by alerque** [comment] 2022-08-04 12:48
Just a heads up...I have already done a major refactor using the other Penlight class syntax. I haven't done anything past that yet, I was reviewing options now.

**Closed** 2022-08-04 15:07 UTC
Labels: bug
