### ISSUE TITLE
Please add support for variable fonts

### ISSUE THREAD

**Issue by ctrlcctrlv** [sile-typesetter/sile#931] opened 2020-07-10 11:13 UTC
Default EB Garamond distribution is now variable...

**Comment by simoncozens** [comment] 2020-07-10 11:26
This is on my radar. The problem is how to represent variable fonts in PDF. PDF doesn't have any support for VF at all, so the strategy has to be to instantiate them as static instances and embed those. I'm waiting on harfbuzz/harfbuzz#2112 to be able to do that static instantiation.

**Comment by alerque** [comment] 2021-08-28 13:51
Issue #1182 is a duplicate of this, but because it includes an action plan of sorts I'm going to close this as the dup.

**Closed** 2021-08-28 13:52 UTC
Labels: duplicate

**Comment by ctrlcctrlv** [comment] 2021-09-03 11:12
That is OK, being the first to complain confers no special privileges, unfortunately. :wink:
