### ISSUE TITLE
Check that color support and font fallbacks don't clash with each other

### ISSUE THREAD

**Issue by simoncozens** [sile-typesetter/sile#239] opened 2015-12-05 09:35 UTC
Load one, then the other; make sure they can still be used.

We may need to subclass the current shaper object (`SILE.shaper { ... }`) instead of the default shaper (`SILE.shapers.shaper { ... }`) - that would allow for multiple subclassing.

But I don't think there is a generally good solution to packages interfering with each other - of course latex suffers from this too.

**Comment by alerque** [comment] 2022-06-24 11:34
This was basically a duplicate of my much later #1244 issue and has been addressed in #1454, to land in the next patch release. There is a test that switches back and forth several times. It isn't 100% of what it could be, but most scenarios work. Loading a color font with the font command and no content blows away the fall fallback enabled shaper. It can be re-enabled of course but it doesn't just come back. On the other hand passing content (e.g. `\font[family=ColorFont]{content}`) will switch to the color shaper only temporarily and then go back to the previous one. Likewise removing the last fallback font in the queue will revert to the previous shaper.

**Closed by alerque** 2022-06-24 11:34 UTC
