### ISSUE TITLE
footnote appearing one page too early in the manual

### ISSUE THREAD

**Issue by raphCode** [sile-typesetter/sile#1609] opened 2022-11-15 22:26 UTC
While reading the manual, I noticed that a footnote appears on the page previous to where to footnote is actually used:
![image](https://user-images.githubusercontent.com/15750438/202037499-34ca8f0a-aa86-4e23-84fa-c94a8d82caec.png)

Is this the intended behavior?
The problem appears on page 73/74 in version [0.14.4](https://sile-typesetter.org/manual/sile-0.14.4.pdf), and the source is here:
https://github.com/sile-typesetter/sile/blob/8d810182c25799fd134133611f3c29e90a60f7c8/documentation/c06-macroscommands.sil#L51

I did not create a MWE because
- I don't know if this is a bug after all
- I don't know Sile yet

**Comment by Omikhleia** [comment] 2022-11-15 22:32
Might be a duplicate of #619

**Comment by Omikhleia** [comment] 2023-03-26 12:39
This is indeed a duplicate of #619 - unfortunately showing in the manual.
Closing as Duplicate.

**Closed** 2023-03-26 12:40 UTC
Labels: duplicate, documentation
