### ISSUE TITLE
Error with numbering=false

### ISSUE THREAD

**Issue by biggnome** [sile-typesetter/sile#1276] opened 2021-11-09 10:07 UTC
Setting this option for sections or subsections throws an error. Should utilities.formatnumber check if num is nil? Adding this into utilities.lua appears to work, but I'm out of my depth here.

**Comment by Omikhleia** [comment] 2021-11-09 10:25
You mean section used before any chapter, right?

SILE 0.12, this works;
```
\begin[papersize=6in x 9in, class=book]{document}

\chapter{Test}

\section[numbering=false]{Test Section}

\end{document}
```
This generates an error:
```
\begin[papersize=6in x 9in, class=book]{document}

% Commented the chapter
% \chapter{Test}

\section[numbering=false]{Test Section}

\end{document}
```

One could argue that a book is composed of chapters first, though ;)

By the way, I'd rather think that the issue is in the book class near line 183 - i.e. when adding the section to the running headers regardless of it having a number or not.

**Comment by biggnome** [comment] 2021-11-09 11:15
Hmm...that compiles just fine. The error I'm getting (`/usr/local/share/sile/core/utilities.lua:524: bad argument #1 to 'abs' (number expected, got nil)`) seems to be related to \included files. This has cropped up for me a couple of times, although I couldn't reproduce it just now with otherwise empty test files containing just chapter and section markup with no other content. I'll try to pin down more specific conditions in the morning. Weird.

**Comment by Omikhleia** [comment] 2021-11-09 19:18
If you reproduce it, I suggest:
- running SILE with the `-t ` option to possibly get a longer trace
- in the book class, look for the "section" command and change this:
  ``` 
      SILE.call("right-running-head", {}, function ()
        SILE.call("book:right-running-head-font")
        SILE.call("rightalign", {}, function ()
          SILE.settings.temporarily(function ()
            SILE.call("show-multilevel-counter", { id = "sectioning", level = 2 })
            SILE.typesetter:typeset(" ")
            SILE.process(content)
          end)
        end)
      end)
  ```
  To this:
  ``` 
      SILE.call("right-running-head", {}, function ()
        SILE.call("book:right-running-head-font")
        SILE.call("rightalign", {}, function ()
          SILE.settings.temporarily(function ()
            if SU.boolean(options.numbering, true) then  -- PATCH HERE
              SILE.call("show-multilevel-counter", { id = "sectioning", level = 2 })
              SILE.typesetter:typeset(" ")
            end
            SILE.process(content)
          end)
        end)
      end)
  ```

**Comment by Omikhleia** [comment] 2021-11-09 19:35
N.B. This is not a proper fix. There are a nest of wrong things here:
- It tries to display the counter while the section was marked not having one.
  - Would there be another numbered section before, we would get that number here!
  - And if there is none, it eventually crashes in \utilities.lua:524: bad argument #1 to 'abs'` indeed, but because `SILE.formatMultilevelCounter` goes beyond the array boundaries. (and `"show-multilevel-counter" would too, if passed a display option...)
  - It typesets the counter, a space, the section title - note that the TOC does the same thing - but these do not honor the pre/post hooks possibly used. These pre/post hooks are a bit broken to that respect (e.g. in one of my tests, I set them to "§" and ". " respectively, got "§1. Section" as section, but obviously not in TOC and headers. I am scrapping that in my own book class, but I am not near to a proper fix...

**Comment by biggnome** [comment] 2021-11-09 23:54
I can confirm this issue seems to surface when it tries to print the section number in the heading (TOC too? Did not investigate that specifically) in which the only section(s) within a chapter are set to `numbering=false`. It does not occur when a preceding numbered section is present (in which case the preceding section's number is displayed in the heading, e.g., "1.1 [name of second, unnumbered section]"), nor when the chapter is short enough not to spill over multiple pages and thereby eliding the error.

**Comment by Omikhleia** [comment] 2021-11-10 00:39
> It does not occur when a preceding numbered section is present (in which case the preceding section's number is displayed in the heading, e.g., "1.1 [name of second, unnumbered section]"),

So this seems to be the same symptom as I pinpointed above. I"ll make a PR for it in the book class, as well as some changes to the multilevel counters, once tested enough in my own book-like class too.

**Comment by Omikhleia** [comment] 2021-11-23 08:50
Made a minimal PR for the issue as reported, without my other comments above, which belong to a broader scope and are best addressed independently. (One could add to them "Why are right running headers disabled on pages without folios", but that's again another type of concern).

**Closed** 2021-12-16 13:02 UTC
Labels: bug
