### ISSUE TITLE
Why table of contents doesn't have yet an option for disable folios on it?

### ISSUE THREAD

**Issue by jodros** [sile-typesetter/sile#1992] opened 2024-02-06 22:34 UTC
Just asking before trying to make new little (and maybe silly) PRs every time...

**Comment by Omikhleia** [comment] 2024-02-06 22:39
Er. I don't get it. In most books I have, the ToC _is_ paginated ;)
References for the contrary?

**Comment by jodros** [comment] 2024-02-06 22:44
Yeah, maybe I could have said about it being an option then...

I've a plenty of books whose toc isn't paginated and many other which they aren't.

**Comment by Omikhleia** [comment] 2024-02-06 22:52
> I've a plenty of books whose toc isn't paginated and many other which they aren't.

Then the issue is perhaps not with ToC _itself_, but in the section of the book where it occurs. I am sure I already mentioned front matter / main matter / back matter in some issue.[^2] Whether the standard book class shall have these distinctions is debatable[^1] but this is the real game, I think?

[^1]: Because it's complex to address, really. I still don't have them either in my resilient book class, and have postponed the question for better days.

[^2]: Here, likely: https://github.com/sile-typesetter/sile/issues/601#issuecomment-907851276

**Comment by Omikhleia** [comment] 2024-02-06 23:00
BTW, this also why I believe the ToC "as-is" should just be a ToC and not have a title-like header -- one of the differences between **resilient.tableofcontents** and the core **tableofcontents**. Do one thing (a ToC), but do it well -- and let the surrounding context know whether (and how) it it needs some sectioning.

**Comment by jodros** [comment] 2024-02-06 23:06
Now you nailed it, I agree! That's the origin of my question, because for me, this header should behave just as a chapter header having no folios on the their page. I just checked for some examples, I could send you several examples of books in different languages whose ToC isn't paginated, at least not in its first page, when it happens to span through a couple of pages...

**Comment by Omikhleia** [comment] 2024-02-06 23:10
> Now you nailed it,

Thanks, lol. These lines might make sense to someone else than me then:
https://github.com/Omikhleia/markdown.sile/blob/774122f15c2f5940ce5637fa5c221d3fd2e29cc8/packages/markdown/commands.lua#L744-L751

**Comment by Omikhleia** [comment] 2024-05-06 20:53
Closing/rejecting: as discussed, folio numbering and ToC are orthogonal topics. One depends on sectioning strategies, and the other is just responsible for generating a ToC.

**Closed by Omikhleia** 2024-05-06 20:53 UTC
Labels: question
