### ISSUE TITLE
Formal specification of SILE grammar documentation

### ISSUE THREAD

**Issue by baubleb** [sile-typesetter/sile#1435] opened 2022-06-15 14:32 UTC
Is the formal specification of the SILE grammar documented?

This would help write other tools such as a Language Server, as per https://github.com/sile-typesetter/sile/issues/1406

**Comment by Omikhleia** [comment] 2022-06-15 16:32
AFAIK, the [LPEG grammar](https://github.com/sile-typesetter/sile/blob/4090a08862e7dda5d1d07d21edf0db07bf692d5f/core/inputs-texlike.lua#L21) is probably the closest thing to a "formal" specification

**Comment by alerque** [comment] 2022-06-15 22:01
No, it isn't. At the moment the LPEG parser source code is the defacto standard. I probably wouldn't bee too hard to come up with an EBNF for it, but such has not been done yet. There are a couple of idiosyncrasies such as the balanced braces requirement is pass-through blocks, but mostly it's pretty straight forward.

**Comment by alerque** [comment] 2022-12-06 17:58
The much ado about #105 is making be serious about writing out a formal grammar spec!

Is there a language that would be preferred for this? I have experience with reading several by eye (mostly EBNF) but not in writing them or parsing them automatically. Would Lark or something else be preferable if I were to dig in to this?

**Comment by nawordar** [comment] 2023-01-25 09:53
> Is there a language that would be preferred for this? I have experience with reading several by eye (mostly EBNF) but not in writing them or parsing them automatically. Would Lark or something else be preferable if I were to dig in to this?

[Tree-sitter](https://tree-sitter.github.io/tree-sitter/) is getting popular. It has bindings to many languages and some editors, e.g. Neovim, support using it for syntax highlighting. Having official tree-sitter grammar would make it easy to create tools for SILE in (almost) any language. I wouldn't call it "formal specification" though.

Zig is using PEG grammar for both documentation and the parser: https://github.com/ziglang/zig-spec/tree/master/grammar. Maybe we could do the same thing?

**Comment by alerque** [comment] 2023-01-25 10:42
Our parser is already written in LPEG so writing up a PEG variant probably wouldn't be that hard. But how does that help? Can a PEG grammar be converted to a tree-sitter grammar automatically?

**Comment by nawordar** [comment] 2023-01-25 11:58
> Can a PEG grammar be converted to a tree-sitter grammar automatically?

I don't think so. I mentioned PEG, because the issue is about formal specification, and tree-sitter uses a JavaScript DSL instead of a separate language ([example](https://github.com/tree-sitter/tree-sitter-javascript/blob/master/grammar.js)). This DSL still looks pretty similar to PEG though, so maybe it's fine.

**Comment by alerque** [comment] 2023-02-14 06:33
c.f. https://github.com/unicode-org/message-format-wg/issues/342 for a relevant discussion of grammars and tooling.

**Comment by alerque** [comment] 2023-02-15 19:21
I started work on an ABNF grammar (which seemed like the best candidate on the grounds that in can be converted to other grammars better than most and hence used in the widest range of tooling), but that may or may not turn out to be a good fit. So far it hasn't gone well.

**Comment by AlexanderMisel** [comment] 2023-06-18 15:31
It would be easier to understand the grammar if the LPeg code is written in LPeg.re format. Below is math grammar in LPeg.re

![math grammar](https://github.com/sile-typesetter/sile/assets/7542439/cb16d0a3-324b-4564-925d-adc2af3bb1d5)

**Comment by alerque** [comment] 2024-01-11 13:49
@brynne8 Do you have that grammar coded up somewhere other than a screen shot? It would be useful to have to play around with if you had it to share.

**Comment by brynne8** [comment] 2024-01-15 04:54
> @brynne8 Do you have that grammar coded up somewhere other than a screen shot? It would be useful to have to play around with if you had it to share.

```lua
local lpeg = require('lpeg')
local re = require('re')
local bits = require('parserbits')
local inspect = require('inspect')

local P, C, S = lpeg.P, lpeg.C, lpeg.S
local myID = C(bits.silidentifier) / 1

local wrapper = function (a) return type(a)=="table" and a or {} end
local specials = S"{}%\\"

local inputter = {}

inputter.passthroughCommands = {
  ftl = true,
  lua = true,
  math = true,
  raw = true,
  script = true,
  sil = true,
  use = true,
  xml = true
}

local isPassthrough = function (_, _, command)
  return inputter.passthroughCommands[command] or false
end
local isNotPassthrough = function (...)
  return not isPassthrough(...)
end

local g = re.compile([=[
document         <- texlike_stuff !.
texlike_stuff    <- {: environment / comment / texlike_text / texlike_braced_stuff / texlike_command :}*

environment      <- '\begin' {:options: %parameters :}
                   ('{' {:command: passthrough_cmd :} '}' passthrough_env_stuff pass_end /
                    '{' {:command: %cmdID :} '}' texlike_stuff notpass_end)

comment          <- ('%' (!%eol .)* %eol ) -> ''
texlike_text     <- { (!%specials . / %escaped_specials)+ } -> unescapeSpecials
texlike_braced_stuff <- '{' texlike_stuff '}'
texlike_command  <- '\' ({:command: passthrough_cmd :} {:options: %parameters :}
                    passthrough_braced_stuff / {:command: %cmdID :} {:options: %parameters :}
                    texlike_braced_stuff)

passthrough_cmd  <- 'ftl' / 'lua' / 'math' / 'raw' / 'script' / 'sil' / 'use' / 'xml'

passthrough_stuff <- { {: passthrough_text / passthrough_debraced_stuff :} }
passthrough_env_stuff <- {: passthrough_env_text :}*
passthrough_text <- { [^{}]+ }
passthrough_env_text <- { (!('\end{' =command '}') .)+ }
passthrough_braced_stuff <- '{' passthrough_stuff '}'
passthrough_debraced_stuff <- { passthrough_braced_stuff }
notpass_end <- '\end{' =command '}' _
pass_end <- '\end{' =command '}' _

_   <- %s*
]=], {
  isPassthrough = isPassthrough,
  isNotPassthrough = isNotPassthrough,
  unescapeSpecials = function (str)
    return str:gsub('\\([{}%%\\])', '%1')
  end,
  cmdID = myID - P"begin" - P"end",
  parameters = (P"[" * bits.parameters * P"]")^-1 / wrapper,
  eol = S"\r\n",
  specials = specials,
  escaped_specials = P"\\" * specials
})

print(inspect(g:match([[
% this is a sample comment
\begin[papersize=a6]{document}
Hello, world!
\end{document}
]])))
```

I used to think that LPeg.re supports `Cb` capture, but found no corresponding rule. So I slightly modified the grammar.

**Comment by alerque** [comment] 2024-01-20 20:36
Thanks @brynne8. I [started setting that up as an alternative parser](https://github.com/alerque/sile/compare/formal-grammar...alerque:sile:lpeg-re). It isn't quite all wired up yet but it will be interesting to benchmark it against the epnf based parser as well as mess around with how useful parser errors could be. One of the reasons it's failing tests right now is it throws different errors than epnf based parsing. If we were to switch by default that would be one less Lua dependency, and I agree the grammar is somewhat easier to grok (at least for me who loves regular expressions)).

Tangentially I also have the ABNF grammar converting to EBNF, which also opens up a lot of options for converting it to other parsers. See [this branch](https://github.com/alerque/sile/compare/formal-grammar...alerque:sile:ebnf).

**Closed** 2024-01-27 20:49 UTC
Labels: todo, documentation

**Comment by alerque** [comment] 2024-01-30 22:23
For anybody following this issue, I've posted some of the formal grammar work including railroad diagrams [on the website](https://sile-typesetter.org/sil-grammar/). The ABNF format grammar also works as input for `apg-c`, `apg-js`, and `apg-py` to generate parsers in those languages. I haven't put the generated parsers through any paces, but the input syntax is at least valid enough to *generate* them without errors. Some developer rules for generating parsers are currently [in this branch](https://github.com/alerque/sile/tree/ebnf).
