### ISSUE TITLE
Name of root element needs to be streamlined

### ISSUE THREAD

**Issue by jamadagni** [sile-typesetter/sile#1052] opened 2020-09-07 09:04 UTC
Hello. I am intrigued about the XML input possibility of SILE because I would like to output structured PDF from a program I am writing. However, it is not clear how to convert a simple document from TeX-like syntax to XML syntax.

For the following TeX-like syntax which works:

```
\begin[papersize=a5]{document}
\font[family="Noto Serif Devanagari", size = 24pt]मम नाम श्रीरमणः
\end{document}
```

The following well-formed XML:

```
<document papersize="a5">
<font family="Noto Serif Devanagari" size="24pt" />
मम नाम श्रीरमणः
</document>
```

doesn't work and produces the following error:

```
sile hello.xml.sil 

This is SILE v0.10.10
<hello.xml.sil>

! This isn't a SILE document! at hello.xml.sil: in <file> (<document papersize="a5">
<font family="Noto Serif Devanagari" size="24pt" />
मम नाम श��)
```

Even if I encode the whole thing in `<sile></sile>` I get:

```! Unknown command document at hello.xml.sil:2:1: in \documenttable: 0x564a6b4c06a0```

Please help!

**Comment by andresantosjor** [comment] 2020-09-08 00:31
The documentation says you can use any XML tag as the root node of the document, however my tests didn't work unless the root node is `sile`. Maybe the "anything you want" was scraped and the documentation needs to be updated?

Anyways, use `<sile>` as root and your document compiles just fine:

`<sile papersize="a5">
    <font family="Noto Serif Devanagari" size="24pt" />
     मम नाम श्रीरमणः
</sile>`

[test.pdf](https://github.com/sile-typesetter/sile/files/5185476/test.pdf)

**Comment by jamadagni** [comment] 2020-09-08 07:54
But if I write `\begin[papersize=a5]{document}` in the one syntax, I expect to write `<document papersize="a5">` in the other, and not `<sile>`.

Another thing is: on p 29 of the SILE book, it says that contents of `\include`d files should be within `\begin{sile}` `\end{sile}` or `<sile>` tags.

IIUC that any and all SILE input should start and end with `document` tags (in both styles). If correct, then one might as well declare that `document` should be the root element of all SILE documents.

I am also not sure what the need to differentiate between documents that `\include` other documents and those that are `\include`d in the matter of the root element and that too only in the case of the TeX style. That is, in the XML style, all documents should be always rooted on `<sile>` but in TeX “main” documents should be rooted on `\begin{document}` but `\include`d ones should be rooted on `\sile`?

I feel this distinction isn't so useful. All `.sil` files of both styles ideally should be able to be rendered separately as well as in `\include`d cases equally. If it is felt that there are potentially conflicting attributes such as document class etc then one may opt for some conflict resolution stategy such as the class of `\include`d documents will be ignored. Maybe some options such as page size can be handled without conflict.

At any rate, this matter of the root element needs to be addressed.

**Comment by simoncozens** [comment] 2020-09-08 12:11
I agree that there's a problem here. It's been a while since I processed XML documents in SILE but my understanding is that any root element *should* work. However, what is normally done is that there is a `.sil` "wrapper" which defines the processing expectations for a non-`sile` root. See the Greek lexicon example:

```
% cd examples/greek-lexicon
% sile -I perseus.sil lexicon.xml
```

`lexicon.xml` begins with a "lexicon" tag, but SILE doesn't know what to do with that, so first we load `perseus.sil` which explains how to turn it into a printable document.

**Comment by simoncozens** [comment] 2020-09-08 12:12
(This is slightly separate to the point about `document` being the top-level of a `.sil` file and `sile` being the top-level of a `.xml` file, which I agree is a problem.)

**Comment by alerque** [comment] 2020-09-10 09:23
I also agree there is a problem here, both in the way this makes application to 3rd party XML hard and the inconsistency with the SIL flavor input.

However this is a duplicate of #508 and I propose continuing discussion and fixes back there.

**Closed by alerque** 2020-09-10 09:23 UTC
