### ISSUE TITLE
Support ctable-like tables

### ISSUE THREAD

**Issue by PanderMusubi** [sile-typesetter/sile#45] opened 2015-02-04 20:49 UTC
Please support tables with the (as much as possible) syntax of cable, see also http://www.ctan.org/tex-archive/macros/latex/contrib/ctable

**Comment by jamadagni** [comment] 2020-09-07 15:12
Hello! SILE doesn't have any existing packages that creates tables?!

**Comment by ctrlcctrlv** [comment] 2020-09-07 17:25
Hi. It does but it is nowhere near as powerful as ctables. I was planning to write a ctables extension for SILE, but it's been bumped down on my priority list. If this is something you'd be willing to pay for you can email me. Until then you can check out some of the examples I've made, like my repository PamudpodUnicodePaper, which contains code for enabling the simpler table that comes with SILE.

**Comment by jamadagni** [comment] 2020-09-08 06:57
Hello and thanks for your reply. Saw your document. Very interesting especially to one who has worked on Indic Unicode, but really there don't seem to be any tables with column in your final document.

**Comment by ctrlcctrlv** [comment] 2020-09-08 07:48
@jamadagni There is, there's a table on the first page with my name and email.

**Comment by jamadagni** [comment] 2020-09-08 09:55
Hello yes. I did see your `.sil` file and it had the `\table` element but
scarcely what would normally be perceived as a table, with multiple columns
and rows.

**Comment by ctrlcctrlv** [comment] 2020-09-08 10:04
...There are multiple columns and rows.

Perhaps you will prefer the example used to build the documentation, although at a base level it is identical, since it looks more ordinary. 😄 

Please see:

https://github.com/sile-typesetter/sile/blob/4a92f58012599bccd1c2ba244004a2602bc4de51/documentation/developers.sil#L31-L48

**Comment by alerque** [comment] 2020-09-10 10:09
SILE's `simpletable` is a starting point, but yes a more advanced table module is definitely something we'd like to have at some point.

For now depending on your use case parallel frames (where each frame is essentially a column and the *sync* functions align content in rows) might be more useful than the current table implementation.

**Comment by simoncozens** [comment] 2021-09-08 12:28
I remember when I tried looking at this many years ago, I was planning to use the [CSS table model](https://www.w3.org/TR/css-tables-3/) which contains some algorithms that might be useful for implementors.

**Comment by Omikhleia** [comment] 2021-10-29 23:44
> Definitely agree with «something is very definitely better than nothing»!

Ok, ok :smile: ... I cleaned up and pushed a decently working version of my "**ptable**" package to my [own package repo](https://github.com/Omikhleia/omikhleia-sile-packages) - It can probably live there for a while, I'm still testing and considering improvements, but it's there if anyone wants to check and try it. It's fully documented (§1.1.8 in the generated documentation) and I hope the code to be commented enough where I erred initially.

And would it seem fit by @simoncozens and @alerque at any convenient step, AFAIC, it could go to the core distribution along with the lower-level "parbox" package on which it relies.

Just for the fun of it - this one example gave me a headache due to a bad bug - one day, the following could happen, count me in:

![image](https://user-images.githubusercontent.com/18075640/139509678-d89e1906-0018-45a5-874e-2e849fe74749.png)

(And on a more personal angle, this "ptable" package is my 15th package. Yeah! Ok some of them are dumb simple, but heh, anyhow I sort of feel closer to being able to start typesetting a book with all the building blocks I need... And it's real fun hacking SILE, lol)

**Comment by Omikhleia** [comment] 2021-11-01 00:01
Added background color for rows and cells, and a "hook" for cell styling.

![image](https://user-images.githubusercontent.com/18075640/139605473-94820369-a7ac-4e75-b1c8-dfae3d536f6f.png)

**Comment by Omikhleia** [comment] 2021-11-01 10:17
Added more flexibility with the cell border options, so that this kind of table (from the `ctable` documentation) is doable - I am told this presentation is frequent is scientific layouts.

![image](https://user-images.githubusercontent.com/18075640/139655937-1aedde45-4fa3-4a7a-bb61-a278aa2fc1f6.png)

AFAIC, the only "missing" features so far could be:
- An easier way to set the borders at the row level. This would just be a convenience to achieve the same result as above, so I won't add it to avoid feature creep, unless it's really demanded.
- Repeating a header row on page breaks. Is the extra complexity worth it? (I seldom have long tables of that type in my own writings)

**Comment by ctrlcctrlv** [comment] 2021-11-01 12:09
> AFAIC, the only "missing" features so far could be:
> *[…]*
> Repeating a header row on page breaks. Is the extra complexity worth it? (I seldom have long tables of that type in my own writings)

I'd say it's worth it, as I plan to use this for Unicode tables (so will often have long tables).

**Comment by Omikhleia** [comment] 2021-11-01 13:51
Added more flexibility with the cell padding options, so that this other table (from the LaTeX `booktabs` package) could be reproduced:
![image](https://user-images.githubusercontent.com/18075640/139681341-a8ece127-69ec-4de5-b16b-c8fbcee33940.png)

Again, settings at cell levels are sufficient, but a bit pedestrian, one could want an easier way to set them at row levels to simplify their typesetting. Still, it would be a convenience rather than an actual feature, so I don't add it for now, as for the borders.

The repeated header is less obvious, due to the way the pagebuilder works (so you might not be any longer in the table enviromnement when boxes are moved until a good break point is found... I'll try to think to it... or maybe you can have a look at it @ctrlcctrlv ?

**Comment by simoncozens** [comment] 2021-11-01 15:24
Do you need a hook from the typesetter from when a new page is started but before all the boxes are put back into it?

**Comment by Omikhleia** [comment] 2021-11-01 16:09
@simoncozens I've a semi-working version just overriding the initNextFrame() method and doing some look up. It sort of works, though I have to take into account potential glues that could be there too and skip them. I wonder whether this is very robust ;)

**Comment by Omikhleia** [comment] 2021-11-01 17:11
Ok, pushed a version with header rows repeated on page breaks. As stated, this could be fragile... The basic test case worked (in the "examples" folder), though. As far as features are concerned, this should be enough?

As an aside note, this beast is not very efficient, performance-wise, on long tables...

**Comment by Omikhleia** [comment] 2021-11-08 23:28
> As an aside note, this beast is not very efficient, performance-wise, on long tables...

Er. No longer true. Bug fixed ^^

**Comment by Omikhleia** [comment] 2023-04-02 14:15
I'm closing this issue:
- Tables are complex, and there are various ways to address them. Let's compare with the TeX ecosystem, FWIW. In these days, I'd bet few people use plain-TeX tables. Many are probably using the LaTeX version of them... But there's a reason too for many competing solutions to exist (ctable, booktabs, tabu... and plenty of others) - It's hard to cover everything and satisfy everybody. That is to say, whatever "core" solution SILE might eventually want, it wouldn't be a definitive answer ;)
- Anyhow, as of a SILE solution, we have my 3rd-party "ptable" as explained above. It doesn't have to be the definitive answer either (and since I once mentioned it... I failed at achieving a "ptable2" re-implementation with extra goodies - perhaps because the initial "ptable" suffice for most of my own needs, or it's just real hard for me to reinvent it on new grounds, having already walked upon a given path!)
- Since 0.13, SILE has a package ecosystem using luarocks. So anyone is now able to propose new packages as part of the ecosystem, and that is really cool. Anyone is free to come with a competing solution, perhaps based on a wholly different approach ;) -- So closing this issue doesn't imply it's necessary fully solved, but I really don't think there's any good reason for keeping it open.

**Closed** 2023-04-02 14:15 UTC
Labels: enhancement
